### PR TITLE
distributed: guard x86 cache-flush intrinsics for aarch64

### PR DESCRIPTION
**Pull request by blozano-tt**
## Problem

`d2h_socket.cpp` unconditionally includes `<immintrin.h>` and calls `_mm_clflush` / `_mm_lfence`, which are x86-only intrinsics. This breaks `Linux/aarch64` builds with a wall of errors from clang-20:

```
immintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"
```

Introduced in #42905.

## Fix

Replace the bare x86 intrinsics with thin inline helpers (`host_clflush` / `host_lfence`) that dispatch to the correct ISA:

| Arch | Cache-line flush | Fence |
|---|---|---|
| x86 / x86-64 | `_mm_clflush` | `_mm_lfence` |
| aarch64 | `DC CIVAC` (clean+invalidate to PoC) | `DSB ISH` |
| other | `#error` | — |

Also renames `k_x86_clflush_line_bytes` → `k_host_clflush_line_bytes` (cache lines are 64 B on both supported arches, so the value is unchanged).

## Notes for reviewers

- `DC CIVAC` + `DSB ISH` is the standard aarch64 equivalent of clflush+lfence for observing device DMA writes through host-mapped memory. Same semantics.
- The `using_hugepage_` path (which contains all these calls) is only reachable when `can_use_pinned_memory` is false — not expected on aarch64 production hardware, but the code must at least compile.
- `--without-distributed` does **not** skip compiling this file (it only gates MPI linking); that is a separate issue.

🧠 _Fixed by BrAIn — my neurons fired on all architectures for once._

### CI Status
_Auto-generated on every push. Badges update live. Click a badge to filter runs by this branch._

- [](https://github.com/tenstorrent/tt-metal/actions/workflows/sanity-tests.yaml?query=branch:brain/aarch64-d2h-socket-fix)
- [](https://github.com/tenstorrent/tt-metal/actions/workflows/runtime-sanity-tests.yaml?query=branch:brain/aarch64-d2h-socket-fix)
- [](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml?query=branch:brain/aarch64-d2h-socket-fix)
- [](https://github.com/tenstorrent/tt-metal/actions/workflows/tt-metal-l2-nightly.yaml?query=branch:brain/aarch64-d2h-socket-fix)
- [](https://github.com/tenstorrent/tt-metal/actions/workflows/all-model-tests.yaml?query=branch:brain/aarch64-d2h-socket-fix)
- [](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select.yaml?query=branch:brain/aarch64-d2h-socket-fix)
- [](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-t3k.yaml?query=branch:brain/aarch64-d2h-socket-fix)
- [](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-galaxy.yaml?query=branch:brain/aarch64-d2h-socket-fix)

### CODE REVIEW

**Comment by mcraigheadTT** [comment]
As this build is not tested in CI: @micahwhiteTT tested the build on aarch64 and this fixes the build error

**Review by jbaumanTT — APPROVED** [review]
The PR description doesn't match the contents of the patch. But the patch itself seems reasonable.
