### ISSUE TITLE
[vLLM nightly] Qwen3-32B Galaxy: force-argmax sampling calls missing TT_CCL.get_and_cycle_ag_semaphore_handles (regression from #49457)

### ISSUE THREAD

**Issue by viktorpusTT** [tenstorrent/tt-metal#50084]
## Summary

`[WH-GLX] Qwen3-32B device with sampling-tests` in the vLLM nightly has been failing since 2026-07-14. The vLLM server never becomes ready because EngineCore crashes during prefill warmup with:

```
AttributeError: 'TT_CCL' object has no attribute 'get_and_cycle_ag_semaphore_handles'.
Did you mean: 'get_and_cycle_barrier_semaphore_handle'?
  File "models/common/sampling/tt_sampling.py", line 615, in forward
    multi_device_global_semaphore=self.tt_ccl.get_and_cycle_ag_semaphore_handles(cluster_axis),
```

Failing job: https://github.com/tenstorrent/tt-metal/actions/runs/29461616422/job/87508984657#step:19:612

## Root cause

PR #49457 ("BH-galaxy qwen3 attention + mlp", commit d536699fbe3, merged 2026-07-14) added a `SAMPLING_AG_CONFIG` block to `models/demos/llama3_70b_galaxy/tt/qwen_model_config.py` with `allow_force_argmax: True`. This enables the force-argmax fast-path in the shared sampling module, but the Galaxy `TT_CCL` does not implement the CCL method that path requires.

Chain:

1. `qwen_model_config.py:327` now sets `self.model_config["SAMPLING_AG_CONFIG"] = {"allow_force_argmax": True, ...}` (new in #49457).
2. That flows to `models/common/sampling/tt_sampling.py:180` -> `self._allow_force_argmax_sampling = True`.
3. Prefill warmup samples greedily (k=1, p=0, temp=1), so `_is_force_argmax_sampling` (`tt_sampling.py:58`) now returns `True`.
4. On the multi-device Galaxy mesh (`num_devices > 1`), `TTSampling.forward` takes the force-argmax all-gather branch at `tt_sampling.py:615`, calling `self.tt_ccl.get_and_cycle_ag_semaphore_handles(cluster_axis)`.
5. For this model `self.tt_ccl` is `models/demos/llama3_70b_galaxy/tt/llama_ccl.py`'s `TT_CCL`, which only implements `get_and_cycle_barrier_semaphore_handle` (line 165) and has never had `get_and_cycle_ag_semaphore_handles`. Confirmed absent in both the current file and #49457's parent commit.

Every other `TT_CCL` the shared sampling module targets (`models/common/modules/tt_ccl.py`, `models/tt_transformers/tt/ccl.py`, `models/demos/deepseek_v3_d_p/tt/tt_ccl.py`, `models/demos/t3000/falcon40b/tt/falcon_ccl.py`) implements `get_and_cycle_ag_semaphore_handles`. The `llama3_70b_galaxy` one predates that convention. #49457 turned on the fast path without adding the method to this CCL.

## Scope

- tt-metal model code only. Not vLLM or the TT plugin.
- Only Qwen3-32B on Galaxy is affected via this route. Llama-3.3-70B Galaxy uses `model_config.py`, which does not set `SAMPLING_AG_CONFIG`, so it is not affected by this bug.

## Fix options

1. **Preferred:** add `get_and_cycle_ag_semaphore_handles(self, cluster_axis=None)` to `models/demos/llama3_70b_galaxy/tt/llama_ccl.py`'s `TT_CCL`, returning AG semaphore handles consistent with the existing all-gather machinery in that class. Keeps the perf win #49457 intended.
2. **Stopgap only:** set `allow_force_argmax: False` in `qwen_model_config.py`. Unblocks nightly but reverts the optimization, so not a real fix.

Regression owner: author of #49457.

**Comment by mgiermakowskiTT** [comment]
https://github.com/tenstorrent/tt-metal/pull/50220 addressed in this PR

**Comment by mgiermakowskiTT** [comment]
The PR got merged in should be resolved now, I will close the issue when the next CI run passes

**Comment by bgoelTT** [comment]
@viktorpusTT I think this can be closed because we had a passing nightly on July 18th https://github.com/tenstorrent/tt-metal/actions/runs/29667116464/job/88142628372

**Comment by mgiermakowskiTT** [comment]
closing for now as it seems to be passing on main as mentioned above, feel free to open if needed
