### ISSUE TITLE
Dangling reference error in kernel.cpp

### ISSUE THREAD

**Issue by ThisIsFineTM** [tenstorrent/tt-metal#20608]
### Describe the bug

```sh
./tt_metal/impl/kernels/kernel.cpp: In member function ‘virtual void tt::tt_metal::DataMovementKernel::read_binaries(tt::tt_metal::IDevice*)’:
./tt_metal/impl/kernels/kernel.cpp:451:27: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
  451 |     ll_api::memory const& binary_mem = llrt::get_risc_binary(
      |                           ^~~~~~~~~~
./tt_metal/impl/kernels/kernel.cpp:451:61: note: the temporary was destroyed at the end of the full expression ‘tt::llrt::get_risc_binary(tt::tt_metal::JitBuildState::get_target_out_path(const std::string&) const(((tt::tt_metal::DataMovementKernel*)this)->tt::tt_metal::DataMovementKernel::tt::tt_metal::Kernel.tt::tt_metal::Kernel::kernel_full_name_), load_type)’
  451 |     ll_api::memory const& binary_mem = llrt::get_risc_binary(
      |                                        ~~~~~~~~~~~~~~~~~~~~~^
  452 |         build_state.get_target_out_path(this->kernel_full_name_),
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  453 |         load_type);
      |         ~~~~~~~~~~                                           
./tt_metal/impl/kernels/kernel.cpp: In member function ‘virtual void tt::tt_metal::EthernetKernel::read_binaries(tt::tt_metal::IDevice*)’:
./tt_metal/impl/kernels/kernel.cpp:485:27: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
  485 |     ll_api::memory const& binary_mem = llrt::get_risc_binary(
      |                           ^~~~~~~~~~
./tt_metal/impl/kernels/kernel.cpp:485:61: note: the temporary was destroyed at the end of the full expression ‘tt::llrt::get_risc_binary(tt::tt_metal::JitBuildState::get_target_out_path(const std::string&) const(((tt::tt_metal::EthernetKernel*)this)->tt::tt_metal::EthernetKernel::tt::tt_metal::Kernel.tt::tt_metal::Kernel::kernel_full_name_), load_type)’
  485 |     ll_api::memory const& binary_mem = llrt::get_risc_binary(
      |                                        ~~~~~~~~~~~~~~~~~~~~~^
  486 |         build_state.get_target_out_path(this->kernel_full_name_),
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  487 |         load_type);
      |         ~~~~~~~~~~                                           
./tt_metal/impl/kernels/kernel.cpp: In member function ‘virtual void tt::tt_metal::ComputeKernel::read_binaries(tt::tt_metal::IDevice*)’:
./tt_metal/impl/kernels/kernel.cpp:531:31: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
  531 |         ll_api::memory const& binary_mem = llrt::get_risc_binary(
      |                               ^~~~~~~~~~
./tt_metal/impl/kernels/kernel.cpp:531:65: note: the temporary was destroyed at the end of the full expression ‘tt::llrt::get_risc_binary(tt::tt_metal::JitBuildState::get_target_out_path(const std::string&) const(((tt::tt_metal::ComputeKernel*)this)->tt::tt_metal::ComputeKernel::tt::tt_metal::Kernel.tt::tt_metal::Kernel::kernel_full_name_), ll_api::memory::Loading::CONTIGUOUS_XIP)’
  531 |         ll_api::memory const& binary_mem = llrt::get_risc_binary(
      |                                            ~~~~~~~~~~~~~~~~~~~~~^
  532 |             build_state.get_target_out_path(this->kernel_full_name_),
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  533 |             ll_api::memory::Loading::CONTIGUOUS_XIP);
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~             
```

### Steps to reproduce the issue

Build on main with GCC 14.2 with -Wextra (-Wdangling-reference)

### Expected behavior

No dangling reference warning

### Please complete the following environment information

Fedora 41.
```
$ gcc --version
gcc (GCC) 14.2.1 20250110 (Red Hat 14.2.1-7)
```

**Comment by ThisIsFineTM** [comment]
I dug into it, and I believe its a false positive in this particular instance. `llrt::get_risc_binary` is returning a reference to a dereferenced pointer, and then the reference is converted back into a pointer to get pushed into the `binaries` collection. The compiler just sees the `const&` binding being passed to something external via pointer then going out of scope, so its triggering the lifetime check. Probably because of the caveat that `const&` creates a lifetime extension for r-values. 

With how its being used, its probably more appropriate for `llrt::get_risc_binary` to return a `ll_api::memory const*` so its more clear that there is no lifetime ownership for the `ll_api::memory const&`.

**Comment by adifrancescoTT** [comment]
Thanks @ThisIsFineTM for the good feedback. I'll identify who is best positioned to action it.

**Comment by ThisIsFineTM** [comment]
@adifrancescoTT @pgkeller @sagarwalTT TL;DR: It actually is a dangling reference in `kernel.cpp`.

Fedora updated to GCC 15, which gave a bit more of a descriptive complaint. Dug into it again and found something I missed the first time around:

kernel.cpp: 485
```cpp
    ll_api::memory const& binary_mem = llrt::get_risc_binary(
        build_state.get_target_out_path(this->kernel_full_name_),
        load_type);
```
`build_state.get_target_out_path` returns a new `std::string`

tt_metal/llrt/llrt.cpp: 45
llrt::get_risc_binary ingests the r-value string via `const&`, then calls `new ll_api::memory`

tt_metal/llrt/tt_memory.cpp: 24
The `memory` constructor ingests the string via `const&` and passes it as an argument to `elf.ReadImage`.

tt_metal/llrt/tt_elffile.cpp: 166
`ElfFile::ReadImage` ingests the string via const& and passes it as an argument to `new Impl`

tt_metal/llrt/tt_elffile.cpp: 59
The string is held by a const& member variable.

So the `ElfFile::Impl` is is holding onto a reference to the temporary string further up the call stack. Which means that the const& down in `ElfFile::Impl` is not extending the lifetime since its not directly binding to the original r-value.

So I am updating my conclusion to "this is definitely a dangling reference".

The change that will fix the issue in the least amount of code is to update `tt_metal/llrt/tt_elffile.cpp:ElfFile::Impl` to hold just a `std::string` instead of a `std::string const&`. 

My personal preference would be to update the call hierarchy to use `std::string_view` instead of `const std::string&` to make the ownership semantics more clear, but changing the ElfFile::Impl would be "good enough" for now.

**Comment by JushBJJ** [comment]
I sometimes gets this error but it goes away if I do a clean build removing `build/`. it wasn't like this before
