### ISSUE TITLE
tt-triage --skip-version-check doesn't work

### ISSUE THREAD

**Issue by philei-tt** [tenstorrent/tt-metal#29216]
### Describe the bug

`--skip-version-check` doesn't disable version check. 
Parsing flag is wrapped in try:...except Exception, which is a bad practice. This hides the following error: 

AttributeError: 'ScriptArguments' object has no attribute 'get'

### Steps to reproduce the issue

You have to have tt-exalens of different version
```
❯ python3 scripts/debugging_scripts/tt-triage.py --skip-version-check
----------------------------------------  ---------------------  -------------------------------------------------------------------------------------------------
scripts/debugging_scripts/tt-triage.py:9  <module>               main()
scripts/debugging_scripts/triage.py:666   main                     _enforce_dependencies(args)
scripts/debugging_scripts/triage.py:541   _enforce_dependencies      raise TTTriageError(message)
scripts/debugging_scripts/triage.py:541   _enforce_dependencies  TTTriageError: Debugger version mismatch.
                                                                   Installed: 0.1.250923+dev.58c6fcf (hash: 58c6fcf)
                                                                   Approved:  hash: 1163365e182db3325629dc8f1aced9af1e278aa4
                                                                 Use scripts/install_debugger.sh to install the approved version, or run with --skip-version-check
```
