### PR TITLE
Integration of Average Pool Operation

### PR DESCRIPTION
**Pull request by jongbinlimTT**
### Ticket
[Add avg_pool2d with kernel size support #14268](https://github.com/tenstorrent/tt-metal/issues/16740)

### Problem description

- Currently, there is no `ttnn` API to support 2D average pooling with different kernel sizes. This PR adds `ttnn.avg_pool2d` with kernel size support. 

Compared to the equivalent pytorch function [torch.nn.functional.avg_pool2d](https://pytorch.org/docs/stable/generated/torch.nn.functional.avg_pool2d.html), for now we only support options with `ceil_mode=False, count_include_pad=True, divisor_override=None`. For different sharding schemes, this PR doesn't include testing WIDTH and BLOCK sharding. However, it has been discussed that different sharding schemes already passed as it is expected. 

### What's changed

- Add `ttnn.avg_pool2d` API
- Change generic pool kernels to support the new `Pool2DType::AVG_POOL2D`
- Add test cases for `ttnn.avg_pool2d`

### Checklist
- [x] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes
<del> [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI passes (if applicable) <del>
- [x] [Model regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml) CI passes (if applicable)
- [x] [Device performance regression](https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml) CI passes (if applicable)
<del> **(For models and ops writers)** Full [new models tests](https://github.com/tenstorrent/tt-metal/actions/workflows/full-new-models-suite.yaml) CI passes (if applicable) <del>
- [x] New/Existing tests provide coverage for changes

### CODE REVIEW

File: ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_wide.cpp [hunk 1]
```diff
@@ -48,12 +48,17 @@ void kernel_main() {
...
 
-    // value of 1 in bf16 in a uin32_t
-    constexpr uint32_t bf16_one_u32 = get_compile_time_arg_val(11);
+    // compile time args
+    // BF16 value packed in UINT32. For maxpool, value is 1.
+    // constexpr uint32_t bf16_one_u32 = get_compile_time_arg_val(11);
+    constexpr uint32_t bf16_scalar = get_compile_time_arg_val(11);  // This scalar is bf16_one_u32 for maxpool.
 
-    constexpr uint32_t in_nblocks_c = get_compile_time_arg_val(12);
+    // DPRINT << "Wide reader kernel - bf16_scalar : " << bf16_scalar << ENDL();
```
Comment (nkpatel-tt) [inline ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_wide.cpp:56]: Remove

**Review by nilaykp — APPROVED** [review]
LGTM, Thanks for nice comments.

File: tests/ttnn/unit_tests/operations/test_avgpool2d.py [hunk 2]
```diff
@@ -0,0 +1,127 @@
...
+    (
+        (1, 1),
+        (2, 2),
+    ),
+)
+@pytest.mark.parametrize(
+    "padding",
+    (
+        (0, 0),
+        (1, 1),
```
Comment (wransom-TT) [inline tests/ttnn/unit_tests/operations/test_avgpool2d.py:106]: We should add more padding combinations, namely (2,2) and (4,4)

File: tests/ttnn/unit_tests/operations/test_avgpool2d.py [hunk 3]
```diff
@@ -0,0 +1,127 @@
...
+    ),
+)
+@pytest.mark.parametrize(
+    "kernel_size",
+    (
+        (2, 2),
+        (3, 3),
+        (5, 5),
+        (9, 9),
+        (13, 13),
```
Comment (wransom-TT) [inline tests/ttnn/unit_tests/operations/test_avgpool2d.py:92]: You can remove the (13,13) combination as we already have two kernel sizes which will hit the large kernel which is sufficient

File: ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_large_kernel_v2.cpp [hunk 4]
```diff
@@ -105,6 +109,12 @@ void kernel_main() {
             cb_reserve_back(in_cb_id, 1);
             uint32_t out_l1_write_addr_base = get_write_ptr(in_cb_id);
             uint32_t out_l1_write_addr = out_l1_write_addr_base;
+
+            // Fill interim buffer with init_value if we have only one chunk.
+            if ((total_elems_to_reduce - processed_rows) < max_rows_for_reduction) {
```
Comment (wransom-TT) [inline ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_large_kernel_v2.cpp:114]: Why was this moved outside the loop?  I think this should still be in the loop since processed rows is being incremented inside the loop, let me know what you think.

File: tests/ttnn/unit_tests/operations/test_avgpool2d.py [hunk 5]
```diff
@@ -0,0 +1,127 @@
...
+)
+def test_run_avg_pool(device, input_shape, kernel_size, stride, padding, dilation, ceil_mode):
+    run_avg_pool(
+        device,
+        input_shape,
+        kernel_size,
+        stride,
+        padding,
+        dilation,
+        # shard_scheme=ttnn.TensorMemoryLayout.HEIGHT_SHARDED,
```
Comment (wransom-TT) [inline tests/ttnn/unit_tests/operations/test_avgpool2d.py:125]: We should also test width and block sharding

File: ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_v2.cpp [hunk 6]
```diff
@@ -67,10 +68,7 @@ void kernel_main() {
     // Reduce scalar = 1
     if (reader_id == 0) {
         cb_reserve_back(in_scalar_cb_id, 1);
-
-        uint32_t bf16_one_u16 = bf16_one_u32 >> 16;
-        // fill 1 row w/ scalar
-        fill_with_val(get_write_ptr(in_scalar_cb_id), ROW_HW, bf16_one_u16);
+        fill_with_val(get_write_ptr(in_scalar_cb_id), ROW_HW, bf16_scalar >> 16);
```
Comment (wransom-TT) [inline ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_v2.cpp:71]: I think this should be TILE_WIDTH not ROW_HW let me know what you think

File: ttnn/cpp/ttnn/operations/pool/generic/device/pool_multi_core_program_factory.cpp [hunk 7]
```diff
@@ -120,6 +152,19 @@ Pool2D::MultiCore::cached_program_t pool2d_multi_core_sharded_with_halo_v2_impl_
     auto in_scalar_cb = tt::tt_metal::CreateCircularBuffer(program, all_cores, in_scalar_cb_config);
     log_debug(tt::LogOp, "CB {} :: PS = {}, NP = {}", in_scalar_cb_id, in_scalar_cb_pagesize, in_scalar_cb_npages);
 
+    // For avgpool, conditionally instantiate and use this CB, which consists of 1s. We don't want to divide
+    // twice by kernel size for large kernel case.
+    if (pool_type == Pool2DType::AVG_POOL2D) {
+        uint32_t in_one_cb_id = tt::CBIndex::c_5;
+        uint32_t in_one_cb_pagesize = tile_size(in_df);
```
Comment (wransom-TT) [inline ttnn/cpp/ttnn/operations/pool/generic/device/pool_multi_core_program_factory.cpp:159]: Does this need to be tile size (1024) or just one row (32)?

File: ttnn/cpp/ttnn/operations/pool/generic/generic_pools_pybind.cpp [hunk 8]
```diff
@@ -116,10 +118,119 @@ void bind_max_pool2d_operation(py::module& module) {
...
+            input_tensor_a (ttnn.Tensor): the tensor to be convolved.
+            batch_size (int): the number of batches (N in a [N, C, H, W] shaped tensor).
+            input_h (int): the height of the input tensor (H in a [N, C, H, W] shaped tensor).
+            input_w (int): the width of the input tensor (W in a [N, C, H, W] shaped tensor).
+            channels (int): the number of channels (C in a [N, C, H, W] shaped tensor).
+            kernel_size (List of [int]): the (h, w) size of the kernel window.
+            stride (List of [int]): the (h, w) stride of the kernel window.
+            padding (List of [int]): the (h, w) padding of the input tensor.
+            ceil_mode (bool): When True, uses 'ceiling' function instead of 'floor' function in the formula to compute output shape. Default: False.
+            count_include_pad (bool): When True, includes zero-padding in the avg calculation. Default: True.
```
Comment (wransom-TT) [inline ttnn/cpp/ttnn/operations/pool/generic/generic_pools_pybind.cpp:144]: Are count_include_pad and divisor_override actually supported yet?

**Review by wransom-TT — CHANGES_REQUESTED** [review]
I made some minor comments, let me know if anything is unclear!

File: ttnn/cpp/ttnn/operations/pool/generic/generic_pools_pybind.cpp (hunk 8 above)
Comment (jongbinlimTT) [reply ttnn/cpp/ttnn/operations/pool/generic/generic_pools_pybind.cpp:144]: Those are not supported yet. This can be a separate task or a PR.

File: tests/ttnn/unit_tests/operations/test_avgpool2d.py (hunk 2 above)
Comment (jongbinlimTT) [reply tests/ttnn/unit_tests/operations/test_avgpool2d.py:106]: Ok, by adding so, we encounter padding size being bigger than half of kernel size. That situation should be an exception, which needs to be added in the test code.

File: tests/ttnn/unit_tests/operations/test_avgpool2d.py (hunk 5 above)
Comment (jongbinlimTT) [reply tests/ttnn/unit_tests/operations/test_avgpool2d.py:125]: Ok, currently, height sharding works and passes. I'll test for other sharding schemes too, but if it fails, support for separate tiles can be a separate task / PR.

File: ttnn/cpp/ttnn/operations/pool/generic/device/pool_multi_core_program_factory.cpp (hunk 7 above)
Comment (jongbinlimTT) [reply ttnn/cpp/ttnn/operations/pool/generic/device/pool_multi_core_program_factory.cpp:159]: This circular buffer should be the same size as the size for the scalar buffer. So, it should be tile size as written in the original implementation.

File: ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_large_kernel_v2.cpp (hunk 4 above)
Comment (jongbinlimTT) [reply ttnn/cpp/ttnn/operations/pool/generic/device/kernels/dataflow/reader_pool_2d_multi_core_sharded_with_halo_large_kernel_v2.cpp:113]: This didn't move outside the loop. This wasn't originally inside the loop. This condition was added additionally to handle the large case reader for avg pool.

File: ttnn/cpp/ttnn/operations/pool/generic/generic_pools_pybind.cpp [hunk 9]
```diff
@@ -32,11 +32,13 @@ void bind_max_pool2d_operation(py::module& module) {
             stride (List of [int]): the (h, w) stride of the kernel window.
             padding (List of [int]): the (h, w) padding of the input tensor.
             dilation (List of [int]): the (h, w) dilation of the kernel window.
+            TODO(jongbinlimTT): ceil_mode should be here in arg, not keyword arg. Needs a fix.
```
Comment (nkpatel-tt) [inline ttnn/cpp/ttnn/operations/pool/generic/generic_pools_pybind.cpp:35]: Please create an issue for this.

File: ttnn/cpp/ttnn/operations/pool/generic/device/kernels/compute/pool_2d_multi_core.cpp [hunk 10]
```diff
@@ -28,9 +28,15 @@ inline void reduce_h_fused(
...
-    tile_regs_acquire();              // paired with tile_regs_release(). Acquire lock on the dest register.
+    // <<<<<<< HEAD:ttnn/cpp/ttnn/operations/pool/generic/device/kernels/compute/pool_2d_multi_core.cpp
+    // const uint32_t curr_in_cb_id = split_reader ? (in_cb_id + (in_stick_index & 0x1)) : in_cb_id;
+    // cb_wait_front(curr_in_cb_id, 1);  // paired with cb_pop_front(curr_in_cb_id, 1);
+    // tile_regs_acquire();              // paired with tile_regs_release(). Acquire lock on the dest register.
+    // =======
+    const uint32_t curr_in_cb_id = (split_reader && (in_stick_index & 0x1)) ? in_cb_id_1 : in_cb_id_0;
+    cb_wait_front(curr_in_cb_id, 1);
+    tile_regs_acquire();
+    // >>>>>>> origin/main:ttnn/cpp/ttnn/operations/pool/generic/device/kernels/compute/max_pool_multi_core.cpp
```
Comment (ayerofieiev-tt) [inline ttnn/cpp/ttnn/operations/pool/generic/device/kernels/compute/pool_2d_multi_core.cpp:39]: need to fix the conflict

Comment (jongbinlimTT) [reply ttnn/cpp/ttnn/operations/pool/generic/device/kernels/compute/pool_2d_multi_core.cpp:39]: Yes, I'm aware of this.

Comment (jongbinlimTT) [reply ttnn/cpp/ttnn/operations/pool/generic/device/kernels/compute/pool_2d_multi_core.cpp:39]: Work in progress. Merge conflict hasn't been resolved yet, and working with @dstoiljkovicTT now. I noted in the commit message.

File: tests/ttnn/unit_tests/operations/test_avgpool2d.py [hunk 11]
```diff
@@ -0,0 +1,154 @@
...
+    ),
+)
+@pytest.mark.parametrize(
+    "padding",
+    (
+        (0, 0),
+        (1, 1),
+        (2, 2),
+        (4, 4),
+        (6, 6),
```
Comment (wransom-TT) [inline tests/ttnn/unit_tests/operations/test_avgpool2d.py:117]: We don't need 6x6 padding

File: tests/ttnn/unit_tests/operations/test_avgpool2d.py [hunk 12]
```diff
@@ -0,0 +1,154 @@
...
+@pytest.mark.parametrize("dilation", ((1, 1),))
+@pytest.mark.parametrize(
+    "ceil_mode",
+    [
+        False,
+        # True # TODO(jongbinlimTT): Need to support.
+    ],
+)
+def test_run_avg_pool(device, input_shape, kernel_size, stride, padding, dilation, ceil_mode):
+    known_issues = [
```
Comment (wransom-TT) [inline tests/ttnn/unit_tests/operations/test_avgpool2d.py:129]: do we need this known issues list?  It seems like the p > k // 2 check would cover all these cases?

**Review by wransom-TT — COMMENTED** [review]
I think my concerns have been largely addressed, I would be ready to approve though it looks like there is some cleanup still required of commented out code and such

**Comment by wransom-TT** [comment]
Oh sorry I forgot one thing also we still want to test width and block sharding if possible, otherwise we can create a new ticket if support for these sharding schemes isn't ready yet

File: tests/ttnn/unit_tests/operations/test_avgpool2d.py (hunk 12 above)
Comment (jongbinlimTT) [reply tests/ttnn/unit_tests/operations/test_avgpool2d.py:129]: Correct. It's just to specify which known issues apply to `p > k // 2' case. I don't need to have it, but it's just to explain more. I think it's actually good to remove it.

File: tests/ttnn/unit_tests/operations/test_avgpool2d.py [hunk 13]
```diff
@@ -0,0 +1,141 @@
...
+
+
+def run_avg_pool(
+    device, input_shape, kernel_size, stride, padding, dilation, memory_config=None, shard_scheme=None, ceil_mode=False
+):
+    ## Test setup for both.
+    in_n, in_c, in_h, in_w = input_shape
+    torch.manual_seed(0)
+    torch_input = torch.rand(input_shape, dtype=torch.bfloat16)
+    # torch_input = torch.zeros(input_shape, dtype=torch.bfloat16)
```
Comment (bbradelTT) [inline tests/ttnn/unit_tests/operations/test_avgpool2d.py:19]: Should this be removed?

**Review by wransom-TT — APPROVED** [review]
LGTM thanks for addressing my comments!

**Review by dstoiljkovicTT — APPROVED** [review]

**Review by dstoiljkovicTT — CHANGES_REQUESTED** [review]
test_avgpool2d.py should moved to the tests/ttnn/unit_tests/operations/pool/ instead of tests/ttnn/unit_tests/operations/ this should reduce the reviewers list

**Review by dstoiljkovicTT — COMMENTED** [review]
These changes have compilation errors when tried to be built with --disable-unity-builds. This must be corrected since the merge queue will remove this due to these errors. Commits should be squashed as well.

**Review by dstoiljkovicTT — APPROVED** [review]

**Review by dstoiljkovicTT — APPROVED** [review]

File: tests/ttnn/unit_tests/operations/pool/test_avgpool2d.py [hunk 14]
```diff
@@ -0,0 +1,141 @@
...
+    ## Test setup for both.
+    in_n, in_c, in_h, in_w = input_shape
+    torch.manual_seed(0)
+    torch_input = torch.rand(input_shape, dtype=torch.bfloat16)
+    # torch_input = torch.zeros(input_shape, dtype=torch.bfloat16)
+    # for n in range(input_shape[0]):
+    #     for c in range(input_shape[1]):
+    #         for h in range(input_shape[2]):
+    #             for w in range(input_shape[3]):
+    #                 torch_input[n, c, h, w] = h * in_w + w
```
Comment (ayerofieiev-tt) [inline tests/ttnn/unit_tests/operations/pool/test_avgpool2d.py:24]: remove commented code please

File: tests/ttnn/unit_tests/operations/pool/test_avgpool2d.py [hunk 15]
```diff
@@ -0,0 +1,141 @@
...
+        (2, 2),
+        (4, 4),
+    ),
+)
+@pytest.mark.parametrize("dilation", ((1, 1),))
+@pytest.mark.parametrize(
+    "ceil_mode",
+    [
+        False,
+        # True # TODO(jongbinlimTT): Need to support.
```
Comment (ayerofieiev-tt) [inline tests/ttnn/unit_tests/operations/pool/test_avgpool2d.py:124]: what is the timeline for this?

File: tests/ttnn/unit_tests/operations/pool/test_avgpool2d.py [hunk 16]
```diff
@@ -0,0 +1,141 @@
...
+        # [1, 112, 112, 112], # TODO(jongbinlimTT): C not multiple of 32.
+        # Case: Normal compute & Wide (C > 256) reader kernel.
+        [1, 512, 16, 16],
+        [1, 800, 16, 16],
+        # [1, 368, 16, 16], # TODO(jongbinlimTT): C not multiple of 32.
+        # Case: All of the above with batch size > 1.
+        [2, 32, 16, 16],
+        [2, 32, 112, 112],
+        [2, 512, 16, 16],
+        [2, 800, 16, 16],
```
Comment (ayerofieiev-tt) [inline tests/ttnn/unit_tests/operations/pool/test_avgpool2d.py:89]: is this on your radar?
https://github.com/tenstorrent/pytorch2.0_ttnn/blob/main/docs/operations/aten.avg_pool2d.default.md

File: tests/ttnn/unit_tests/operations/pool/test_avgpool2d.py (hunk 15 above)
Comment (jongbinlimTT) [reply tests/ttnn/unit_tests/operations/pool/test_avgpool2d.py:124]: @wransom-TT can provide better insight for this.

File: tests/ttnn/unit_tests/operations/pool/test_avgpool2d.py (hunk 16 above)
Comment (jongbinlimTT) [reply tests/ttnn/unit_tests/operations/pool/test_avgpool2d.py:89]: This doesn't seem to be on my radar.

File: tests/ttnn/unit_tests/operations/pool/test_avgpool2d.py [hunk 17]
```diff
@@ -0,0 +1,141 @@
...
+    # torch_input = torch.zeros(input_shape, dtype=torch.bfloat16)
+    # for n in range(input_shape[0]):
+    #     for c in range(input_shape[1]):
+    #         for h in range(input_shape[2]):
+    #             for w in range(input_shape[3]):
+    #                 torch_input[n, c, h, w] = h * in_w + w
+
+    ## Test setup for Actual.
+    input_tensor = torch.permute(torch_input, (0, 2, 3, 1))
+    input_tensor = torch.reshape(input_tensor, (1, 1, in_n * in_h * in_w, in_c))
```
Comment (ayerofieiev-tt) [inline tests/ttnn/unit_tests/operations/pool/test_avgpool2d.py:28]: This is not exactly the torch pattern users use.
usually users work with unmodified (not permuted and reshaped) in torch.
those operations seem to only be required by our call of the avg_pool2d (and other pool and conv ops).

Please reflect that in the test.

**Review by dstoiljkovicTT — CHANGES_REQUESTED** [review]
This change is introducing slow down in resnet. This should be sorted out before merging.

**Comment by jongbinlimTT** [comment]
@dstoiljkovicTT is going to take over from now. Thank you all!
