### ISSUE TITLE
[Bug Report] `fmt::print` logger fails to compile during runtime under C++20

### ISSUE THREAD

**Issue by marty1885** [tenstorrent/tt-metal#7761]
**Describe the bug**
Metalium applications fails to compile with GCC 13.2.1 under C++20 mode. This is due to libfmt enabling `constexpr` check when C++20 is detected.

I've attached an one line fix. Can we just merge it?

**To Reproduce**
1. Build metalium as usual
2. Clone my vector addition example `git clone https://github.com/marty1885/ttVecAdd`
3. Set C++ mode to C++20 (edit `CMakeLists.txt`, make is say `set(CMAKE_CXX_STANDARD 20)`
4. Compile and see the error

```
In file included from /home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/assert.hpp:15,
                 from /home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/core_coord.h:14:
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp: In instantiation of ‘void tt::Logger::log_level_type(Level, tt::LogType, const char*, Args&& ...) [with Args = {long unsigned int}]’:
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:216:33:   required from ‘void tt::log_info(LogType, const char*, Args&& ...) [with Args = {long unsigned int}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/bfloat16.hpp:123:13:   required from here
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:123:23:   in ‘constexpr’ expansion of ‘fmt::v10::basic_format_string<char, long unsigned int>(fmt)’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:123:23: error: ‘fmt’ is not a constant expression
  123 |             fmt::print(*fd, fmt, std::forward<Args>(args)...);
      |             ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp: In instantiation of ‘void tt::Logger::log_level_type(Level, tt::LogType, const char*, Args&& ...) [with Args = {long unsigned int, float&, unsigned int&}]’:
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:216:33:   required from ‘void tt::log_info(LogType, const char*, Args&& ...) [with Args = {long unsigned int, float&, unsigned int&}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/bfloat16.hpp:199:13:   required from here
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:123:23:   in ‘constexpr’ expansion of ‘fmt::v10::basic_format_string<char, long unsigned int, float&, unsigned int&>(fmt)’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:123:23: error: ‘fmt’ is not a constant expression
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp: In instantiation of ‘void tt::Logger::log_level_type(Level, tt::LogType, const char*, Args&& ...) [with Args = {int&, int&, long unsigned int}]’:
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:216:33:   required from ‘void tt::log_info(LogType, const char*, Args&& ...) [with Args = {int&, int&, long unsigned int}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/bfloat16.hpp:212:13:   required from here
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:123:23:   in ‘constexpr’ expansion of ‘fmt::v10::basic_format_string<char, int&, int&, long unsigned int>(fmt)’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:123:23: error: ‘fmt’ is not a constant expression
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp: In instantiation of ‘void tt::Logger::log_level_type(Level, tt::LogType, const char*, Args&& ...) [with Args = {const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}]’:
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:246:33:   required from ‘void tt::log_fatal(LogType, const char*, Args&& ...) [with Args = {const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:251:14:   required from ‘void tt::log_fatal(const char*, Args&& ...) [with Args = {const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/assert.hpp:118:14:   required from ‘void tt::assert::tt_assert_log_message(const char*, const Ts& ...) [with Ts = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/assert.hpp:133:30:   required from ‘void tt::assert::tt_throw(const char*, int, const std::string&, const char*, const Ts& ...) [with Ts = {char [42], std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}; std::string = std::__cxx11::basic_string<char>]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/core_coord.h:80:9:   required from here
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:123:23:   in ‘constexpr’ expansion of ‘fmt::v10::basic_format_string<char, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&>(fmt)’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:123:23: error: ‘fmt’ is not a constant expression
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp: In instantiation of ‘void tt::Logger::log_level_type(Level, tt::LogType, const char*, Args&& ...) [with Args = {}]’:
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:246:33:   required from ‘void tt::log_fatal(LogType, const char*, Args&& ...) [with Args = {}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:251:14:   required from ‘void tt::log_fatal(const char*, Args&& ...) [with Args = {}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/assert.hpp:118:14:   required from ‘void tt::assert::tt_assert_log_message(const char*, const Ts& ...) [with Ts = {}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/assert.hpp:133:30:   required from ‘void tt::assert::tt_throw(const char*, int, const std::string&, const char*, const Ts& ...) [with Ts = {const char*}; std::string = std::__cxx11::basic_string<char>]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/core_coord.h:245:15:   required from here
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:123:23:   in ‘constexpr’ expansion of ‘fmt::v10::basic_format_string<char>(fmt)’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:123:23: error: ‘fmt’ is not a constant expression
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp: In instantiation of ‘void tt::Logger::log_level_type(Level, tt::LogType, const char*, Args&& ...) [with Args = {const unsigned int&, const unsigned int&}]’:
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:246:33:   required from ‘void tt::log_fatal(LogType, const char*, Args&& ...) [with Args = {const unsigned int&, const unsigned int&}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:251:14:   required from ‘void tt::log_fatal(const char*, Args&& ...) [with Args = {const unsigned int&, const unsigned int&}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/assert.hpp:118:14:   required from ‘void tt::assert::tt_assert_log_message(const char*, const Ts& ...) [with Ts = {unsigned int, unsigned int}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/assert.hpp:133:30:   required from ‘void tt::assert::tt_throw(const char*, int, const std::string&, const char*, const Ts& ...) [with Ts = {char [93], unsigned int, unsigned int}; std::string = std::__cxx11::basic_string<char>]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/impl/buffers/circular_buffer_types.hpp:40:13:   required from here
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:123:23:   in ‘constexpr’ expansion of ‘fmt::v10::basic_format_string<char, const unsigned int&, const unsigned int&>(fmt)’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:123:23: error: ‘fmt’ is not a constant expression
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp: In instantiation of ‘void tt::Logger::log_level_type(Level, tt::LogType, const char*, Args&& ...) [with Args = {const unsigned char&, const unsigned int&}]’:
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:246:33:   required from ‘void tt::log_fatal(LogType, const char*, Args&& ...) [with Args = {const unsigned char&, const unsigned int&}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:251:14:   required from ‘void tt::log_fatal(const char*, Args&& ...) [with Args = {const unsigned char&, const unsigned int&}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/assert.hpp:118:14:   required from ‘void tt::assert::tt_assert_log_message(const char*, const Ts& ...) [with Ts = {unsigned char, unsigned int}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/assert.hpp:133:30:   required from ‘void tt::assert::tt_throw(const char*, int, const std::string&, const char*, const Ts& ...) [with Ts = {char [71], unsigned char, unsigned int}; std::string = std::__cxx11::basic_string<char>]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/impl/buffers/circular_buffer_types.hpp:51:13:   required from here
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:123:23:   in ‘constexpr’ expansion of ‘fmt::v10::basic_format_string<char, const unsigned char&, const unsigned int&>(fmt)’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:123:23: error: ‘fmt’ is not a constant expression
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp: In instantiation of ‘void tt::Logger::log_level_type(Level, tt::LogType, const char*, Args&& ...) [with Args = {const unsigned char&}]’:
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:246:33:   required from ‘void tt::log_fatal(LogType, const char*, Args&& ...) [with Args = {const unsigned char&}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:251:14:   required from ‘void tt::log_fatal(const char*, Args&& ...) [with Args = {const unsigned char&}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/assert.hpp:118:14:   required from ‘void tt::assert::tt_assert_log_message(const char*, const Ts& ...) [with Ts = {unsigned char}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/assert.hpp:133:30:   required from ‘void tt::assert::tt_throw(const char*, int, const std::string&, const char*, const Ts& ...) [with Ts = {char [119], unsigned char}; std::string = std::__cxx11::basic_string<char>]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/impl/buffers/circular_buffer_types.hpp:57:13:   required from here
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:123:23:   in ‘constexpr’ expansion of ‘fmt::v10::basic_format_string<char, const unsigned char&>(fmt)’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:123:23: error: ‘fmt’ is not a constant expression
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp: In instantiation of ‘void tt::Logger::log_level_type(Level, tt::LogType, const char*, Args&& ...) [with Args = {const unsigned int&, const long unsigned int&}]’:
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:246:33:   required from ‘void tt::log_fatal(LogType, const char*, Args&& ...) [with Args = {const unsigned int&, const long unsigned int&}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:251:14:   required from ‘void tt::log_fatal(const char*, Args&& ...) [with Args = {const unsigned int&, const long unsigned int&}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/assert.hpp:118:14:   required from ‘void tt::assert::tt_assert_log_message(const char*, const Ts& ...) [with Ts = {unsigned int, long unsigned int}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/assert.hpp:133:30:   required from ‘void tt::assert::tt_throw(const char*, int, const std::string&, const char*, const Ts& ...) [with Ts = {char [90], unsigned int, long unsigned int}; std::string = std::__cxx11::basic_string<char>]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/impl/buffers/circular_buffer_types.hpp:115:13:   required from here
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:123:23:   in ‘constexpr’ expansion of ‘fmt::v10::basic_format_string<char, const unsigned int&, const long unsigned int&>(fmt)’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:123:23: error: ‘fmt’ is not a constant expression
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp: In instantiation of ‘void tt::Logger::log_level_type(Level, tt::LogType, const char*, Args&& ...) [with Args = {const unsigned int&}]’:
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:246:33:   required from ‘void tt::log_fatal(LogType, const char*, Args&& ...) [with Args = {const unsigned int&}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:251:14:   required from ‘void tt::log_fatal(const char*, Args&& ...) [with Args = {const unsigned int&}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/assert.hpp:118:14:   required from ‘void tt::assert::tt_assert_log_message(const char*, const Ts& ...) [with Ts = {unsigned int}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/assert.hpp:133:30:   required from ‘void tt::assert::tt_throw(const char*, int, const std::string&, const char*, const Ts& ...) [with Ts = {char [66], unsigned int}; std::string = std::__cxx11::basic_string<char>]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/core_descriptor.hpp:86:9:   required from here
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:123:23:   in ‘constexpr’ expansion of ‘fmt::v10::basic_format_string<char, const unsigned int&>(fmt)’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:123:23: error: ‘fmt’ is not a constant expression
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp: In instantiation of ‘void tt::Logger::log_level_type(Level, tt::LogType, const char*, Args&& ...) [with Args = {const int&}]’:
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:246:33:   required from ‘void tt::log_fatal(LogType, const char*, Args&& ...) [with Args = {const int&}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:251:14:   required from ‘void tt::log_fatal(const char*, Args&& ...) [with Args = {const int&}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/assert.hpp:118:14:   required from ‘void tt::assert::tt_assert_log_message(const char*, const Ts& ...) [with Ts = {int}]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/assert.hpp:133:30:   required from ‘void tt::assert::tt_throw(const char*, int, const std::string&, const char*, const Ts& ...) [with Ts = {char [46], int}; std::string = std::__cxx11::basic_string<char>]’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/impl/dispatch/dispatch_core_manager.hpp:162:13:   required from here
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:123:23:   in ‘constexpr’ expansion of ‘fmt::v10::basic_format_string<char, const int&>(fmt)’
/home/marty/Documents/not-my-projects/tt-metal/tt_metal/common/logger.hpp:123:23: error: ‘fmt’ is not a constant expression
make[2]: *** [CMakeFiles/ttvecadd.dir/build.make:76: CMakeFiles/ttvecadd.dir/ttvecadd.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/ttvecadd.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

```

**Expected behavior**
It should compile normally.

**Screenshots**

**Please complete the following environment information:**
- OS: Arch Linux
- Commit: `5e0d2b8b94670710701fed556bf07f900b454ac7`
- Compiler GCC 13.2.1

**Additional context**

**Comment by tt-rkim** [comment]
@marty1885 Please post your PR for the one-line fix

**Comment by tt-rkim** [comment]
Note that we are planning C++20 support, but it is not coming any time soon.

**Comment by marty1885** [comment]
@tt-rkim Sorry I tagged the PR with the wrong issue ID. It's here
https://github.com/tenstorrent/tt-metal/pull/7762

Please merge it.

**Comment by TT-billteng** [comment]
seems to break with our gcc and c++17

Does it compile with gcc 13.2 and c++17?

**Comment by marty1885** [comment]
It compiles for me. Let me install an Ubuntu installation and see what happens

**Comment by tt-rkim** [comment]
@marty1885 Any update?

**Comment by tt-rkim** [comment]
@marty1885 Any update? We may move this down in priority if we don't receive a response on this issue soon.

cc: @milank94 @mbahnasTT @smehtaTT

**Comment by marty1885** [comment]
Hi, sorry I was busy and finally got time working on TT stuff again. No, this is still an issue on my Arch machine.

**Comment by tt-rkim** [comment]
@vtangTT @yan-zaretskiy any issues you guys saw during our C++20 upgrades with `fmt`?

**Comment by vtangTT** [comment]
Yes, I saw the same issue when fixing bugs for C++20 and fixed in basically the same way as can be seen here: https://github.com/tenstorrent/tt-metal/blob/cbb7fb8182a29724ba33402c3ea2dc67d8eb6c73/tt_metal/common/assert.hpp#L112

but I don't believe this should be the long term fix as printing doesn't need to be a runtime operation. I only did this to get C++20 in ASAP. Correct me if I'm wrong @yan-zaretskiy

**Comment by tt-rkim** [comment]
@marty1885
We are currently in the middle of upgrading our C++ version to C++20. We will also use a much newer version of Clang (17 or higher) for compilation.

Please continue using what's in main branch for now. We will update this issue once this is done: https://github.com/tenstorrent/tt-metal/pull/9070/files

**Comment by razorback3** [comment]
Fixed in #9943. Please check it out.
I think this issue can be closed as completed.

**Comment by tt-rkim** [comment]
@marty1885 have you taken a look?

**Comment by marty1885** [comment]
Yup. I have been using the latest tt-metal with GCC and C++20 for my GGML work the past week. Closing the issue.
