### ISSUE TITLE
[tt-train] tt-train examples use old missing config paths and api functions

### ISSUE THREAD

**Issue by imichalakTT** [tenstorrent/tt-metal#35664]
### Component / Area

tt-train

### Issue Type (optional)

Other

### Observed

Running some of the tt-train examples (tt-train/source/examples/...) causes errors due to missing config files and api functions.

Two example instances:

1. Running mnist_mlp example
```bash
./build/sources/examples/mnist_mlp/mnist_mlp
terminate called after throwing an instance of 'YAML::BadFile'
  what():  bad file: /home/imichalak/tenstorrent/tt-metal/tt-train/configs/training_mnist_mlp.yaml
Aborted (core dumped)
```

2. Running tt-train/sources/examples/python/transformers/training.py
```bash
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[7], line 7
      4 sys.path.append(f'{os.environ["TT_METAL_HOME"]}[/tt-train/sources/ttml](http://127.0.0.1:8888/tt-train/sources/ttml)')
      6 import ttml
----> 7 from ttml.common.config import get_config, DeviceConfig, TrainingConfig
      8 from ttml.common.utils import set_seed, initialize_device, create_optimizer
      9 from ttml.common.model_factory import TransformerModelFactory

ImportError: cannot import name 'get_config' from 'ttml.common.config' ([/home/imichalak/tenstorrent/tt-metal/python_env/lib/python3.10/site-packages/ttml/common/config.py](http://127.0.0.1:8888/python_env/lib/python3.10/site-packages/ttml/common/config.py))
```

Breaking changes were made in https://github.com/tenstorrent/tt-metal/commit/f0eece2693d2935b42d36f7a1191d5b6e711ae9e.

### Expected

Examples use updated config paths and API functions.

### 1. Steps (exact commands)

Build tt-train and run:
```
./build/sources/examples/mnist_mlp/mnist_mlp
```

### 2. Input data / link or description

n\a

### 3. Frequency

always

### 1. Software Versions

main branch after https://github.com/tenstorrent/tt-metal/commit/f0eece2693d2935b42d36f7a1191d5b6e711ae9e

### 2. Hardware Details

n\a

### Is this a regression?

Unknown

### Priority

None
