### ISSUE TITLE
Blackhole nightly ttnn group 12 - static_assert(block_ct_dim <= 8, "block_ct_dim must be less than or equal to 8");

### ISSUE THREAD

**Issue by williamlyTT** [tenstorrent/tt-metal#23800]
Breaking ttnn group 12 (seen on both p100 and p150)
https://github.com/tenstorrent/tt-metal/actions/runs/15761995231/job/44431111227#step:6:16170

```
FAILED tests/ttnn/unit_tests/operations/pool/test_upsample.py::test_bilinear_multi_core[math_approx_mode=True-math_fidelity=MathFidelity.LoFi-shard_strategy=ShardStrategy.HEIGHT-batch_size=1-num_channels=288-height=8-width=8-scale_h=2-scale_w=2-device_params={'l1_small_size': 24576}] - RuntimeError: TT_THROW @ /project/tt_metal/impl/program/program.cpp:134: tt::exception
[...]
/work/.ttnn_runtime_artifacts/tt_metal/third_party/tt_llk/tt_llk_blackhole/llk_lib/llk_pack_untilize.h:140:32: error: static assertion failed: block_ct_dim must be less than or equal to 8
  140 |     static_assert(block_ct_dim <= 8, "block_ct_dim must be less than or equal to 8");
      |                   ~~~~~~~~~~~~~^~~~
/work/.ttnn_runtime_artifacts/tt_metal/third_party/tt_llk/tt_llk_blackhole/llk_lib/llk_pack_untilize.h:140:32: note: the comparison reduces to '(9 <= 8)'
```

Reverted breaking change with https://github.com/tenstorrent/tt-metal/pull/23799

TTNN group 12 on blackhole runs as part of blackhole nightly: https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-nightly-tests.yaml

**Comment by pmilenkovicTT** [comment]
Closing as this is fixed.
