### ISSUE TITLE
`main` Failing to build on Arch Linux with GCC 15.2

### ISSUE THREAD

**Issue by marty1885** [tenstorrent/tt-metal#28482]
tt-metal fails to build on Arch Linux with GCC 15.2 due to the following error

```
In file included from /home/marty/Documents/tt/tt-metal/.cpmcache/tt-logger/48ec77b63c35cf84c47678990aa3603b492d0c7c/include/tt-logger/tt-logger.hpp:9,
                 from /home/marty/Documents/tt/tt-metal/tt_stl/tt_stl/reflection.hpp:29,
                 from /home/marty/Documents/tt/tt-metal/build/CMakeFiles/metal_common_pch.dir/cmake_pch.hxx:19,
                 from <command-line>:
/home/marty/Documents/tt/tt-metal/tt_metal/lite_fabric/host_util.cpp: In function ‘void lite_fabric::LaunchLiteFabric(tt::Cluster&, const tt::tt_metal::Hal&, const SystemDescriptor&, const std::filesystem::__cxx11::path&)’:
/home/marty/Documents/tt/tt-metal/tt_metal/lite_fabric/host_util.cpp:177:20: error: cannot bind packed field ‘config.lite_fabric::FabricLiteConfig::binary_size’ to ‘volatile unsigned int&’
  177 |             config.binary_size);
      |             ~~~~~~~^~~~~~~~~~~
ninja: build stopped: subcommand failed.
```
