### ISSUE TITLE
[Build] create_venv.sh execution failed with AttributeError: module 'pkgutil' has no attribute 'ImpImporter'

### ISSUE THREAD

**Issue by aliaksei-sala** [tenstorrent/tt-metal#20849]
### Describe the bug

After upgrading Ubuntu from version 22.04 to 24.04, running create_venv.sh failed with an error.

```
PYTHON_ENV_DIR='pyenvtest' ./create_venv.sh
Creating virtual env in: pyenvtest
Forcefully using a version of pip that will work with our view of editable installs
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cpu
Collecting pip==21.2.4
  Using cached pip-21.2.4-py3-none-any.whl.metadata (4.2 kB)
Using cached pip-21.2.4-py3-none-any.whl (1.6 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.0
    Uninstalling pip-24.0:
      Successfully uninstalled pip-24.0
Successfully installed pip-21.2.4
Setting up virtual env
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ubuntu/tt-metal/pyenvtest/lib/python3.12/site-packages/pip/__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "/home/ubuntu/tt-metal/pyenvtest/lib/python3.12/site-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/ubuntu/tt-metal/pyenvtest/lib/python3.12/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/ubuntu/tt-metal/pyenvtest/lib/python3.12/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/ubuntu/tt-metal/pyenvtest/lib/python3.12/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/home/ubuntu/tt-metal/pyenvtest/lib/python3.12/site-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/home/ubuntu/tt-metal/pyenvtest/lib/python3.12/site-packages/pip/_internal/configuration.py", line 21, in <module>
    from pip._internal.exceptions import (
  File "/home/ubuntu/tt-metal/pyenvtest/lib/python3.12/site-packages/pip/_internal/exceptions.py", line 7, in <module>
    from pip._vendor.pkg_resources import Distribution
  File "/home/ubuntu/tt-metal/pyenvtest/lib/python3.12/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2164, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```

Workaround:
1. Comment out line 28: `#pip install --force-reinstall pip==21.2.4` in create_venv.sh
2. Run `create_venv.sh `(executes successfully)
3. Run `source pyenvtest/bin/activate`
4. Manually install ttnn :
```
pip install dist/ttnn-0.57.0rc60.dev74+ggbc823c4433.any-cp312-cp312-linux_x86_64.whl
```

Follow-up bug: Manual ttnn installation is needed because create_venv.sh:38 `pip install -e .` failed to install ttnn into pyenv without any warnings/errors

@ayerofieiev-tt 

### Steps to reproduce the issue

Steps to reproduce
1. Go to the tt-metal repository
2. Execute create_venv.sh script
3. Observe the error described above.

### Expected behavior

create_venv.sh executes successfully, and the ttnn package is correctly installed in the pyenv environment.

### Please complete the following environment information

- OS: Ubuntu 24.04.2 LTS
- Python version : 3.12.3
- tt-metal commit: 1302cc6b5edd270a40f9 (Date:   Thu Apr 17 13:50:49)

**Comment by tt-rkim** [comment]
@blozano-tt has run into this issue as well. I seem to have lost the relevant issue... do you know what it was called? I tried searching for 3.12 and 24.04 but I couldn't find the relevant one.

Please use 22.04 to unblock yourself. It seems like you are developing for ttnn. We formally ask you use to 22.04 per our installation instructions.

This is because you need a higher version of pip to use with Python 3.12 which we do not support yet for our development flow.

**Comment by tt-rkim** [comment]
24.04 and higher Python version support is not on our radar for a while.

Please unblock yourself with 22.04.
