### PR TITLE
gather: fix missing tile_size_bytes declarations in writer kernels

### PR DESCRIPTION
**Pull request by blozano-tt**
## Summary

Fixes a regression introduced in #42663 (commit `50970dc`). During merge conflict resolution, the `input_tensor_tile_size_bytes` and `output_tensor_tile_size_bytes` `constexpr` declarations were accidentally dropped from both gather writer kernels, while their usages in `noc.async_read`/`noc.async_write` calls were retained. This caused a compile failure:

```
error: 'input_tensor_tile_size_bytes' was not declared in this scope
error: 'output_tensor_tile_size_bytes' was not declared in this scope
```

**Files fixed:**
- `gather_writer_single_row_single_core.cpp`
- `gather_writer_single_row_multi_core.cpp`

**Fix:** Add `constexpr uint32_t {input,output}_tensor_tile_size_bytes = get_tile_size({input,output}_tensor_cb_index);` in the tensor config section, matching the pattern already used in the reader kernels.

## Test plan
- [ ] WH ttsim `gather` op tests pass

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CI Status
_Auto-generated on every push. Badges update live. Click a badge to filter runs by this branch._

- [](https://github.com/tenstorrent/tt-metal/actions/workflows/sanity-tests.yaml?query=branch:brain/fix-gather-writer-tile-size)
- [](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml?query=branch:brain/fix-gather-writer-tile-size)
- [](https://github.com/tenstorrent/tt-metal/actions/workflows/tt-metal-l2-nightly.yaml?query=branch:brain/fix-gather-writer-tile-size)
- [](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select.yaml?query=branch:brain/fix-gather-writer-tile-size)
- [](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-t3k.yaml?query=branch:brain/fix-gather-writer-tile-size)
- [](https://github.com/tenstorrent/tt-metal/actions/workflows/pipeline-select-galaxy.yaml?query=branch:brain/fix-gather-writer-tile-size)

### CODE REVIEW

**Comment by mcraigheadTT** [comment]
I checked out this branch locally and confirmed that this fixes the regression I'm seeing in tests/ttnn/unit_tests/operations/data_movement/test_tosa_gather.py, testing run on WH ttsim:
```
========================================================================== short test summary info ==========================================================================
PASSED tests/ttnn/unit_tests/operations/data_movement/test_tosa_gather.py::test_tosa_gather_general[N=2-K=5-C=3-W=4]
PASSED tests/ttnn/unit_tests/operations/data_movement/test_tosa_gather.py::test_tosa_gather_general[N=1-K=1-C=1-W=1]
PASSED tests/ttnn/unit_tests/operations/data_movement/test_tosa_gather.py::test_tosa_gather_general[N=4-K=4-C=4-W=4]
PASSED tests/ttnn/unit_tests/operations/data_movement/test_tosa_gather.py::test_tosa_gather_general[N=128-K=64-C=128-W=32]
PASSED tests/ttnn/unit_tests/operations/data_movement/test_tosa_gather.py::test_tosa_gather_general[N=16-K=16-C=16-W=16]
PASSED tests/ttnn/unit_tests/operations/data_movement/test_tosa_gather.py::test_tosa_gather_general[N=2-K=256-C=2-W=32]
PASSED tests/ttnn/unit_tests/operations/data_movement/test_tosa_gather.py::test_tosa_gather_general[N=2-K=32-C=96-W=32]
PASSED tests/ttnn/unit_tests/operations/data_movement/test_tosa_gather.py::test_tosa_gather_general[N=1-K=2048-C=1-W=32]
PASSED tests/ttnn/unit_tests/operations/data_movement/test_tosa_gather.py::test_tosa_gather_general[N=64-K=128-C=256-W=128]
PASSED tests/ttnn/unit_tests/operations/data_movement/test_tosa_gather.py::test_tosa_gather_general[N=128-K=128-C=128-W=64]
====================================================================== 10 passed, 1 warning in 19.03s =======================================================================
```

**Comment by mcraigheadTT** [comment]
ttnn-unit-tests sanity has passed. ttsim-integration-tests has some failures, but they appear to be the preexisting ones that I am already fixing: https://github.com/tenstorrent/tt-metal/actions/runs/24693812474

**Comment by mcraigheadTT** [comment]
A separate fix was already merged; was not 100% obvious at first
