### ISSUE TITLE
[Bug Report] Building with ccache enabled fails on Arch Linux but works on Ubuntu

### ISSUE THREAD

**Issue by JushBJJ** [tenstorrent/tt-metal#18079]
**Describe the bug**
Building tt-metal with ccache fails natively on arch but works on my ubuntu 22.04 docker
ccache version (arch & ubuntu): v4.10.2
clang++-17 version (arch & ubuntu): v17.0.6
Full Log: https://pastecode.io/s/71jooccm

Error:
```
In file included from /home/jush/tt-metal-latest/build_Release/ttnn/CMakeFiles/ttnn_operations_experimental_transformer.dir/Unity/unity_3_cxx.cxx:7:
In file included from /home/jush/tt-metal-latest/ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads/nlp_concat_heads.cpp:5:
In file included from /home/jush/tt-metal-latest/ttnn/cpp/ttnn/operations/experimental/transformer/nlp_concat_heads/device/nlp_concat_heads_device_operation.hpp:9:
/home/jush/tt-metal-latest/ttnn/cpp/ttnn/common/queue_id.hpp:19:37: error: use of undeclared identifier 'uint8_t'
   19 | using QueueId = tt::stl::StrongType<uint8_t, struct QueueIdTag>;
      |                                     ^
/home/jush/tt-metal-latest/ttnn/cpp/ttnn/common/queue_id.hpp:20:14: error: unknown type name 'QueueId'
   20 | static const QueueId DefaultQueueId = QueueId(0);
      |              ^
/home/jush/tt-metal-latest/ttnn/cpp/ttnn/common/queue_id.hpp:20:39: error: use of undeclared identifier 'QueueId'
   20 | static const QueueId DefaultQueueId = QueueId(0);
      |                                       ^
```

**Fix**
What I did to simply fix this error was edit `ttnn/cpp/ttnn/common/queue_id.hpp` and add this line:
```cpp
#include <cstdint>
```

Thing is that this patch wasn't needed for Ubuntu, it would just build as normal without any changes...super weird.

Full file:
```cpp
(.venv-3.10) jush@ranedeer:~/tt-metal-latest (main)
$ cat ttnn/cpp/ttnn/common/queue_id.hpp
// SPDX-FileCopyrightText: © 2025 Tenstorrent Inc.
//
// SPDX-License-Identifier: Apache-2.0

#pragma once

#include <strong_type.hpp>
#include <cstdint> // Added this

namespace ttnn {
/*
    Type must be moved to metal.
    Background:
    We have two software command queues available to overlap some work and reduce latency.
    For example, Op2 can be prepared in a different queue while the first queue is blocked, waiting for data readout by
    Op1. TT-NN operations allow specifying which queue should be used. The default queue is 0, and the possible values
    are 0 and 1.
*/
using QueueId = tt::stl::StrongType<uint8_t, struct QueueIdTag>;
static const QueueId DefaultQueueId = QueueId(0);

}  // namespace ttnn

// Exporting to tt::tt_metal namespace because ttnn
// defines some of its own types (think Tensor) in tt::tt_metal namespace.
namespace tt::tt_metal {
using QueueId = ttnn::QueueId;
}
```

**To Reproduce**
0. Run on arch
1. Clone tt-metal
2. Install dependencies
3. Run `sudo ./build_metal.sh --enable-ccache --release --build-programming-examples --cxx-compiler-path=clang++-17 --c-compiler-path=clang-17`

**Expected behavior**
Building tt-metal with ccache enabled should be built without any issues

**Screenshots**
N/A

**Please complete the following environment information:**
- OS: Artix Linux
- Commit: https://github.com/tenstorrent/tt-metal/commit/e68353dfc72bd5bdf3827b93d5e301085f316857

**Additional context**
Building without ccache and the patches works perfectly fine

**Comment by ayerofieiev-tt** [comment]
Let’s add this include! Thank you, @JushBJJ
