### PR TITLE
[LLK] Restore the unary SFPU coverage lane

### LINKED ISSUE #883: SFPU Gelu test compilation fails when compiled with coverage
### Describe the bug

```
In function 'sfpi::vFloat ckernel::sfpu::_calculate_pos_cdf_appx_(sfpi::vFloat)':
E           cc1plus: warning: 'ISRA.1542' is used uninitialized in this function [-Wuninitialized]
E           cc1plus: warning: 'ISRA.1542' is used uninitialized in this function [-Wuninitialized]
E           cc1plus: warning: 'ISRA.1542' is used uninitialized in this function [-Wuninitialized]
E           cc1plus: warning: 'ISRA.1542' is used uninitialized in this function [-Wuninitialized]
E           cc1plus: warning: 'ISRA.1542' is used uninitialized in this function [-Wuninitialized]
E           cc1plus: warning: 'ISRA.1542' is used uninitialized in this function [-Wuninitialized]
E           In file included from ../tt_llk_blackhole/common/inc/ckernel_sfpu.h:12,
E                            from sources/eltwise_unary_sfpu_test.cpp:41:
E           In member function 'void sfpi::__vBase::assign(sfpi::__rvtt_vec_t)',
E               inlined from 'sfpi::vFloat sfpi::vFloat::operator=(sfpi::vFloat)' at sfpi/include/sfpi.h:360:59,
E               inlined from 'sfpi::vFloat ckernel::sfpu::_calculate_pos_cdf_appx_(sfpi::vFloat)' at ../tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_cdf.h:46:18:
E           sfpi/include/sfpi.h:787:7: error: cannot write sfpu vector to memory
E             787 |     v = (initialized) ? __builtin_rvtt_sfpassign_lv(v, in) : in;
E                 |     ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
E           Illegal rvtt builtin found in conditional tree: sfpxloadi
E           ../tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_cdf.h:15: confused by earlier errors, bailing out
```

### Steps to reproduce the issue

Clear all cache from your repo (eg. git clean -xid)
```
git switch ajankovic/code-coverage
cd tests/
pytest --coverage ./python_tests/test_eltwise_unary_sfpu.py 
```

In the test file put these paremeters to isolate faulty test case L#24:
```
@parametrize(
    test_name="eltwise_unary_sfpu_test",
    formats=input_output_formats(
        [
            DataFormat.Float32,
            DataFormat.Float16,
            DataFormat.Float16_b,
            DataFormat.Bfp8_b,
        ]
    ),
    approx_mode=[ApproximationMode.No],# ApproximationMode.Yes],
    mathop=[
        # MathOperation.Abs,
        # MathOperation.Atanh,
        # MathOperation.Asinh,
        # MathOperation.Acosh,
        # MathOperation.Cos,
        # MathOperation.Log,
        # MathOperation.Reciprocal,
        # MathOperation.Sin,
        # MathOperation.Sqrt,
        # MathOperation.Rsqrt,
        # MathOperation.Square,
        # MathOperation.Celu,
        # MathOperation.Silu,
        MathOperation.Gelu,
        # MathOperation.Neg,
        # MathOperation.Fill,
        # MathOperation.Elu,
        # MathOperation.Exp,
        # MathOperation.Exp2,
        # MathOperation.Hardsigmoid,
        # MathOperation.Threshold,
        # MathOperation.ReluMax,
        # MathOperation.ReluMin,
    ],
    dest_acc=[DestAccumulation.No], #DestAccumulation.Yes],
)
def test_eltwise_unary_sfpu_float(test_name, formats, approx_mode, mathop, dest_acc):
```

Comment this out so you actually run the test L#81:
```    if TestTargetConfig().with_coverage and mathop in MathOperation.Gelu:
        pytest.skip(
            reason="When this mathop gets compiled with coverage, compilation error is encountered, LLK issue link is in the comment"
        )```


### Expected behavior

_No response_

### Actual behavior

_No response_

### Please complete the following environment information

_No response_

### LINKED ISSUE #33268: SFPU kernel loop unrolling produces invalid assembly when compiling with coverage infrastructure
### Describe the bug

Example code:
```
template <bool APPROXIMATION_MODE, bool HAS_BASE_SCALING, int ITERATIONS>
inline void _calculate_log_(const int iterations, uint log_base_scale_factor)
{
#pragma GCC unroll 8
    for (int d = 0; d < iterations; d++)
    {
        _calculate_log_body_<HAS_BASE_SCALING>(log_base_scale_factor);
        sfpi::dst_reg++;
    }
}
```

Doesn't get compiled correctly when coverage is turned on.
The snippet is from: ./tt-llk/tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_log.h:L#108

The bug is present on both wormhole and blackhole cards

### Steps to reproduce the issue

```
git clone tt-llk
git switch ajankovic/coverage-loop-unrolling-repro
cd tests
./setup_testing_environment
./reproduce_sfpi_bug.sh
```

We traced that loop unrolling causes an issue, because when it's removed in above and similar code snippets, everything works as intended.

Dumps of both versions of math.elf will appear under names *_math_elf_dump.txt in ./tt-llk/tests
Main difference difference is the ammount of sfpload instructions in coverage versions, there are a lot less of them there.

### PR DESCRIPTION
**Pull request by ldjurovicTT**
### PR Category

LLK test infrastructure.

### Summary

`COVERAGE_COMPILE_SKIP_OPS` in `test_eltwise_unary_sfpu.py` excluded 21 unary SFPU ops from the coverage build, on the grounds recorded in the comment above it: their `#pragma GCC unroll X` loops miscompiled to invalid assembly under `-fprofile-arcs -ftest-coverage`. That was true of the sfpi release the guard was written against. It is not true of the release this branch pins (7.77.0), nor of the newest one (7.78.0), so the guard now only hides those ops from the coverage report.

This PR does three things, in three commits:

1. **Remove `COVERAGE_COMPILE_SKIP_OPS`** — the 21-op list above, plus the `pytest.skip` branch that consumed it and the two call-site comments that named it.
2. **Fix the coverage readback** (`helpers/test_config.py`) — it calls a ttexalens API the pinned `tt-exalens==0.3.31` no longer offers, so *every* coverage test on silicon failed inside the harness before reaching a kernel. Separate commit; ask and I will split it into its own PR.
3. **Narrow the broad-profile coverage skip** — it skipped every `BROAD_SWEEP_OPS` member citing tenstorrent/tt-llk#1435, whose symptom no longer reproduces. Replaced by a per-arch table whose only entry is `Reciprocal` on Blackhole, pointing at #56751.

Net effect on the coverage lane: **614 → 5169 variants passing on Blackhole**, and the Wormhole lane keeps its `Reciprocal` variants as well, with the only coverage-gated op being the one #56751 describes, on the one arch where it reproduces.

Closes #33268
Closes tenstorrent/tt-llk#883
Relates to #56751

### What was measured

sfpi 7.77.0 (the pin) and 7.78.0 (newest release), on blackhole and wormhole. Note that `tests/sfpi` had drifted to 7.74.0, which cannot build this branch at all (`'lreg_pressure' is not a member of 'sfpi'`), so the guard had not been re-tested against a working toolchain in some time.

**1. Compilation.** Bypassing the guard with a pytest plugin — no source edit — and compiling every variant of all 21 ops:

| arch | coverage | no coverage |
|---|---|---|
| blackhole | 2856 passed / 553 skipped | 2856 passed / 553 skipped |
| wormhole | 3302 passed / 107 skipped | 3302 passed / 107 skipped |

Identical splits, so the residual skips are the format/`dest_acc` arch skips rather than anything coverage-related. No assembler errors on either arch on either release.

**2. Codegen equivalence.** A raw `objdump` diff is not the right comparison, because coverage legitimately changes two things that have nothing to do with the algorithm: it inhibits inlining, so `calculate_<op>` stays out-of-line instead of being folded into `run_kernel`; and it interleaves scalar gcov counter updates into the loop body, which shortens the contiguous run GCC can record into the SFPU replay buffer. All `tt*`/`tti*` instructions are dropped from the comparison for the same reason — `ttreplay`, `ttincrwc` and the teardown `ttstallwait` differ by construction.

Comparing the `sfp*` stream only, after flattening the call graph:

| | static `sfp*` | executed `sfp*` |
|---|---|---|
| BH, sfpi 7.77.0 | 18/21 identical | **21/21 identical** |
| BH, sfpi 7.78.0 | 18/21 identical | **21/21 identical** |
| WH, sfpi 7.77.0 | 18/21 identical | **21/21 identical** |

The same three ops account for every static difference, and it is purely replay-window packing:

| op | replay window, no coverage | replay window, coverage | executed `sfp*` |
|---|---|---|---|
| `hardsigmoid` | `ttreplay 0,10` × 8 | `ttreplay 0,7` × 8 | 79 = 79 |
| `threshold` | `ttreplay 0,5` × 8 | `ttreplay 0,4` × 7 | 36 = 36 |
| `negative` | `ttreplay 0,8` × 8 | `ttreplay 0,4` × 16 | 50 = 50 |

Same work, packed into shorter windows replayed more times. Resolve `ttreplay` and the executed stream matches instruction for instruction, operand for operand, for every op.

**3. tt-llk#883 specifically.** That issue is a different failure from #33268 and worth separating. It was sfpi rejecting the uninitialised `sfpi::vFloat result` in `_calculate_pos_cdf_appx_`:

```
sfpi/include/sfpi.h:787:7: error: cannot write sfpu vector to memory
Illegal rvtt builtin found in conditional tree: sfpxloadi
```

Nothing in the tree includes `ckernel_sfpu_cdf.h` any more, so the op sweep cannot reach that function and "GeluAppx compiles under coverage" would not have proven anything about it. I compiled `_calculate_pos_cdf_appx_` and `_calculate_cdf_appx_` directly, using the harness's own math-thread command line with its coverage flags: clean on 7.77.0 and 7.78.0, no error and no `-Wuninitialized` warning, 73 `sfp*` instructions emitted with the gcov counter attached, so it is real code and not optimised away.

### Effect on the coverage job

23 variants move from skipped to passing, all three of the guarded ops that sit outside `BROAD_SWEEP_OPS`:

| op | variants newly compiled |
|---|---|
| `LogWithBase` | 10 |
| `GeluAppx` | 8 |
| `GeluDerivative` | 5 |

Coverage-build totals for the file go from 598 passed / 6091 skipped to 621 / 6068, with nothing lost. That was the effect of commit 1 alone. Commit 3 then brings back the rest of the broad profile as well — see the narrowing section below — so the file's coverage lane ends at 5169 passing variants.

The non-coverage lane is untouched: the guard sits behind `if not TestConfig.WITH_COVERAGE: return`. Collection is unchanged at 6689 on both arches, and the 21 ops still compile without coverage.

### Hardware results (Blackhole p150, sfpi 7.77.0)

Added after the first review pass, because the codegen argument above deserved a silicon check.

| run | configuration | result |
|---|---|---|
| A | whole file, no coverage, file alone | 5311 passed / 1364 skipped / 14 xfailed / **0 failed** |
| B | whole file, `--coverage`, commit 1's guards | 614 passed / 6068 skipped / 7 xfailed / **0 failed** |

So the three ops this PR unskips pass on hardware under coverage, not just through the assembler. The 14 xfails in A are the documented `Sign`/`Heaviside` signed-zero divergences, non-strict and unrelated.

One prerequisite worth flagging separately: the coverage readback path in `helpers/test_config.py` does not run at all against the pinned `tt-exalens==0.3.31`. `read_coverage_data_from_device` calls `parse_elf(Path)` where the signature is `parse_elf(elf_path: str)` (the native `ElfFile` binding rejects a `PosixPath`), and then uses `elf.symbols[...]`, which that release replaced with `find_symbol_by_name`. Every coverage test on silicon fails in the harness before it reaches a kernel — including ops untouched by this PR, and reproducibly on `origin/main`. Nobody had hit it because the LLK coverage lane is `coverage: false` in `tests/pipeline_reorg/llk_e2e_tests.yaml`. Commit 2 fixes it.

### Narrowing the broad-profile skip

The natural next question was whether the other 18 ops can come back too. Bypassing the #1435 skip entirely:

| run | configuration | result |
|---|---|---|
| C | whole file, `--coverage`, #1435 skip bypassed | 5265 passed / 1364 skipped / 14 xfailed / **46 failed** |

All 46 failures are `Reciprocal`, and the cause has nothing to do with suite isolation:

| `Reciprocal`, 153 variants, file alone | result |
|---|---|
| no coverage | 153 passed / **0 failed** |
| `--coverage` | 107 passed / **46 failed** (deterministic across two runs) |
| `--coverage --disable-sfploadmacro` | 153 passed / **0 failed** |

Its failure signature is a golden mismatch in which *alternate* elements are correct and the ones between them are garbage — half the lanes get stale data, which reads as a macro/Dst-indexing fault rather than an accuracy problem. Its `sfp*` stream is byte-identical between the two builds, so the interleaved scalar gcov counters are perturbing the macro sequence's issue timing, not its codegen. That is filed as **#56751**.

It also means the "`sfp*` streams match, therefore behaviour matches" argument earlier in this PR is not sufficient on its own for SFPLOADMACRO ops — which is exactly why the hardware runs are here.

So the blanket profile skip becomes a per-arch table with one entry, `Reciprocal` on Blackhole, and everything else runs:

| run | configuration | result |
|---|---|---|
| E | whole file, `--coverage`, narrowed skip (BH) | 5169 passed / 1509 skipped / 11 xfailed / **0 failed** |

The 1509 skips are the 1364 format/`dest_acc` arch skips a non-coverage run also takes, plus exactly 145 `Reciprocal` variants and nothing else (verified by diffing the skipped node ids against a non-coverage run). Coverage collection completes and merges 624 `.info` files, so the lane produces real data rather than just going green.

`_skip_coverage_unsupported` stays a helper called from all four unary sweeps even though two of their op pools cannot select `Reciprocal` today. The exclusion table is per-op, so a pool that later gains an excluded op is covered without touching the sweep — which has already been needed once, when `ReluMin` joined `_INT_UNARY_OPS`.

**tenstorrent/tt-llk#1435 is closed.** Its repro is the binary and unary suites in one pytest session; `pytest test_eltwise_binary.py test_eltwise_binary_sfpu.py test_eltwise_unary_sfpu.py` as a single invocation on this card gives 10646 passed / 2381 skipped / 20 xfailed / **0 failed** over 12471 variants.

### Review follow-ups

Four points came back on the first version of the narrowed skip. All four were correct; what changed:

**1. `Reciprocal` is not the only sweep op that emits SFPLOADMACRO, so macro emission cannot be the criterion.** Confirmed. `calculate_exponential` takes its macro branch under `APPROXIMATION_MODE && CLAMP_NEGATIVE`, and the four unary sweeps hardcode `CLAMP_NEGATIVE(True)`, so `Exp` at `ApproximationMode.Yes` is instantiated with 16 of them; `calculate_signbit` emits them unconditionally outside `DISABLE_SFPLOADMACRO`; `ckernel_sfpu_unary_max_min.h` has 13, reached by the `_INT_UNARY_OPS` max/min ops. All of them pass under coverage on both arches. In the built ELFs on Wormhole, each `Signbit` `math.elf` carries 8 `SFPLOADMACRO` and each `Reciprocal` one carries 0 — which is also what makes the zero below a real zero rather than an undecoded mnemonic.

So the rule "an op that starts emitting SFPLOADMACRO belongs here too" is gone. The table is now explicitly empirical — *re-measure the op under `--coverage` on the arch in question before adding it* — with the macro documented as the mechanism rather than the criterion.

**2. The exclusion was arch-unconditional but the evidence was Blackhole-only.** Also confirmed, and measured on a Wormhole n300 with the same sfpi 7.77.0:

| `Reciprocal`, 168 Wormhole variants, file alone | result |
|---|---|
| no coverage | 162 passed / 6 xfailed / **0 failed** |
| `--coverage` (skip bypassed) | 162 passed / 6 xfailed / **0 failed** |

Identical splits. The mechanism cannot apply there: `calculate_reciprocal` reaches the hand-written `_calculate_reciprocal_fast_*` macro sequences only on Blackhole, and Wormhole's pure sfpi Newton path emits no `SFPLOADMACRO` at all — 0 in all 12 built `math.elf`s, against 8 per ELF for `Signbit` on the same card. The entry is now `{ChipArchitecture.BLACKHOLE: [MathOperation.Reciprocal]}`, so Wormhole keeps those 168 variants in its coverage lane.

Whole-file confirmation on the same card, with the guard as it now stands:

| run | configuration | result |
|---|---|---|
| WH-1 | whole file, no coverage | 6377 passed / 293 skipped / 19 xfailed / **0 failed** |
| WH-2 | whole file, `--coverage` | 6377 passed / 293 skipped / 19 xfailed / **0 failed** |

Identical, and not just in the totals: the skipped node ids are the same set in both, zero coverage-only and zero non-coverage-only, so on Wormhole the coverage build now costs no variants at all. 6377 + 293 + 19 = 6689, the full collection. None of the 293 is a `Reciprocal` variant; on Blackhole 145 of them are, which is the coverage the arch-unconditional entry was discarding. Collection completed too — 656 `.info` files generated, 636 combined — so commit 2's readback fix is confirmed on Wormhole as well as Blackhole.

**Quasar**, the second half of that comment: it cannot be measured, and not because of coverage. `CHIP_ARCH=quasar --compile-producer` over `Sqrt`/`Log`/`Celu` gives **662 failed either way** — with `--coverage` and without, same counts and same signatures (352 × `fatal error: llk_unpack_A.h: No such file or directory`, 310 × a format-inference `ValueError` at `helpers/data_format_inference.py:713`). This file does not build for Quasar in this harness at all, so removing the 21-op guard exposes nothing new there; the Quasar gap is a separate, pre-existing one.

**3. `test_matmul_and_unary_sfpu.py` still carried the retired rationale.** It did — a bare `# SFPI Issue link:` with no link, then the `#pragma GCC unroll X` claim this PR retires. Rewritten to say what is actually true: the miscompile no longer reproduces on the pinned sfpi, the skip stays because that sweep parametrizes `Reciprocal` (#56751), and the test is `@skip_for_blackhole @skip_for_wormhole` today, so there is no arch on which its coverage build has been measured. I kept the decorator rather than deleting it for that last reason — the only arch left is Quasar, where the sweep does not build (see above) and `ckernel_sfpu_recip.h` has no `SFPLOADMACRO` anyway.

**4. `test_sfpu_plot.py::test_sfpu_stress` had no coverage gate.** Not intended — it drives three `Reciprocal` cases and the exclusion table is module-private, so it now carries `@skip_for_coverage` like its sibling `accuracy/test_sfpu_accuracy.py`.

**5. The guard did not consult `TT_METAL_DISABLE_SFPLOADMACRO`.** Fixed: `_skip_coverage_unsupported` returns early when it is set, so `--coverage --disable-sfploadmacro` runs all `Reciprocal` variants — which is the config the evidence table above already has at 153 passed / 0 failed. Every one of the 36 arch × coverage × macro-disable × op combinations was probed directly; the only skip is Blackhole + coverage + macro enabled + `Reciprocal`.

### Notes for reviewers

- The silicon side is covered on both arches now: runs A/B/C/E on Blackhole p150, runs WH-1/WH-2 plus the `Reciprocal` table on Wormhole n300. Note the LLK coverage lane is off in CI (`coverage: false`), so this PR changes nothing in the current pipeline; it is a prerequisite for turning that lane back on.
- One incidental observation on #33268, offered as a hypothesis rather than a finding: its evidence was "the main difference is the amount of `sfpload` instructions in coverage versions, there are a lot less of them there". That is exactly what replay-buffer packing looks like in an ELF dump — a body recorded once into the replay buffer and re-issued N times appears once statically, so counting `sfpload` undercounts it. I could not confirm this against the original report, because the `ajankovic/coverage-loop-unrolling-repro` branch no longer exists and the toolchain it was filed against is not the pinned one. Worth keeping in mind if a similar report comes in: compare the executed stream, not the static instruction counts.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Review by fvranicTT — APPROVED** [review]

File: tt_metal/tt-llk/tests/python_tests/test_eltwise_unary_sfpu.py [hunk 1]
```diff
@@ -158,58 +158,34 @@
...
-#   https://github.com/tenstorrent/tt-llk/issues/883
-# Covers ops from both sweep profiles.
-COVERAGE_COMPILE_SKIP_OPS = [
-    MathOperation.Acosh,
-    MathOperation.Log,
-    MathOperation.Log1p,
+
+# Ops that return wrong results under coverage instrumentation, so they are skipped only
+# when WITH_COVERAGE is set. Reciprocal is the only op in the sweep that emits
+# SFPLOADMACRO, and the gcov counters interleaved into its loop perturb the macro
```
[the remark this answers is not in the document]
Comment (ldjurovicTT) [reply tt_metal/tt-llk/tests/python_tests/test_eltwise_unary_sfpu.py]: Confirmed, and the rule was wrong as written — thanks, this is the substantive one.

Checked against the tree: `calculate_exponential` takes its macro branch under `APPROXIMATION_MODE && CLAMP_NEGATIVE`, and all four unary sweeps hardcode `CLAMP_NEGATIVE(True)` (lines 664, 746, 1260), so `Exp` at `ApproximationMode.Yes` is instantiated with it; `calculate_signbit` emits them unconditionally outside `DISABLE_SFPLOADMACRO`; and `ckernel_sfpu_unary_max_min.h` has 13, reached by the `_INT_UNARY_OPS` max/min ops. Not just in the headers either — counting the mnemonic in the **coverage-built** `math.elf` of a Wormhole sweep that passes 6377/6377:

| op | `SFPLOADMACRO` in coverage-built `math.elf` | coverage result |
|---|---|---|
| `Exp`, `ApproximationMode.Yes` | 16 | passes |
| `Signbit` | 8 | passes |
| `UnaryMax/MinUint32` | 8 | passes |
| `Reciprocal` (WH) | **0** | passes |

So macro emission does not predict failure, and the "an op that starts emitting SFPLOADMACRO belongs here too" rule is gone. Rescoped exactly as you suggest: the table is now explicitly empirical — *re-measure the op under `--coverage` on the arch in question before adding it* — with the macro recorded as the mechanism rather than the criterion. That also removes the contradiction with the `_int` call-site comment, which I have rewritten to say the int max/min ops emit macros and pass.

(Incidentally this is also what makes the `0` for Reciprocal above meaningful rather than an undecoded mnemonic — the same `objdump` invocation finds 8 and 16 elsewhere.)

File: tt_metal/tt-llk/tests/python_tests/test_eltwise_unary_sfpu.py [hunk 2]
```diff
@@ -158,58 +158,34 @@
...
-    MathOperation.Hardsigmoid,
-    MathOperation.Threshold,
-    MathOperation.ReluMax,
-    MathOperation.ReluMin,
-    MathOperation.Tanh,
-    MathOperation.Gelu,
-    MathOperation.GeluDerivative,
-    MathOperation.LogWithBase,
-    MathOperation.GeluAppx,
 ]
```
[the remark this answers is not in the document]
Comment (ldjurovicTT) [reply tt_metal/tt-llk/tests/python_tests/test_eltwise_unary_sfpu.py]: Right on both halves. Measured on a Wormhole n300 with the same pinned sfpi 7.77.0.

**Reciprocal alone, file alone, 168 Wormhole variants:**

| configuration | result |
|---|---|
| no coverage | 162 passed / 6 xfailed / **0 failed** |
| `--coverage`, skip bypassed | 162 passed / 6 xfailed / **0 failed** |

Identical splits, so `153/153` on Wormhole is confirmed and the entry is now `{ChipArchitecture.BLACKHOLE: [MathOperation.Reciprocal]}`. Your mechanism was right too: `calculate_reciprocal` reaches the hand-written `_calculate_reciprocal_fast_*` sequences only on Blackhole, and Wormhole's pure sfpi Newton path emits **0** `SFPLOADMACRO` in all 12 built `math.elf`s, in the same audit that finds 8 per ELF for `Signbit`.

**Whole file on the same card, with the guard as it now stands:**

| run | configuration | result |
|---|---|---|
| WH-1 | no coverage | 6377 passed / 293 skipped / 19 xfailed / **0 failed** |
| WH-2 | `--coverage` | 6377 passed / 293 skipped / 19 xfailed / **0 failed** |

Identical, and not only in the totals — the skipped node ids are the same set in both, zero coverage-only and zero non-coverage-only. So on Wormhole the coverage build now costs no variants at all, and none of the 293 is a `Reciprocal` variant (on Blackhole 145 of them are, which is the coverage the arch-unconditional entry was discarding). 6377 + 293 + 19 = 6689, the full collection. Coverage collection completed as well — 656 `.info` files generated, 636 combined — so commit 2's readback fix is confirmed on Wormhole too.

**Quasar**: cannot be measured, and coverage is not the reason. `CHIP_ARCH=quasar --compile-producer` over `Sqrt`/`Log`/`Celu` gives **662 failed either way**, with `--coverage` and without — same counts, same signatures (352 × `fatal error: llk_unpack_A.h: No such file or directory`, 310 × a format-inference `ValueError` at `helpers/data_format_inference.py:713`). This file does not build for Quasar in this harness at all, so lifting the 21-op guard exposes nothing new there; that gap is separate and pre-existing. Worth its own issue, but not something this PR can move.

File: tt_metal/tt-llk/tests/python_tests/test_eltwise_unary_sfpu.py [hunk 3]
```diff
@@ -158,58 +158,34 @@
...
-        )
-
-    if mathop in COVERAGE_COMPILE_SKIP_OPS:
+    if mathop in COVERAGE_SFPLOADMACRO_SKIP_OPS:
         pytest.skip(
-            reason="`#pragma GCC unroll X` loops in these ops compile to invalid "
-            "assembly under coverage instrumentation: "
-            "https://github.com/tenstorrent/tt-metal/issues/33268 , "
-            "https://github.com/tenstorrent/tt-llk/issues/883"
+            reason="SFPLOADMACRO returns wrong results under coverage instrumentation: "
```
[the remark this answers is not in the document]
Comment (ldjurovicTT) [reply tt_metal/tt-llk/tests/python_tests/test_eltwise_unary_sfpu.py]: Both fair.

**`test_matmul_and_unary_sfpu.py`** — agreed, closing #33268 and tt-llk#883 while that comment stood was contradictory. Rewritten to what is actually true: the miscompile no longer reproduces on the pinned sfpi, the skip stays because that sweep parametrizes `Reciprocal` (#56751), and the test is `@skip_for_blackhole @skip_for_wormhole` today so its coverage build is unmeasured on every arch we have. I kept the decorator rather than deleting it for that last reason — the only arch left is Quasar, where the sweep does not build at all (see the thread above: 662 failed with and without `--coverage`) and where `ckernel_sfpu_recip.h` has no `SFPLOADMACRO` anyway. Happy to delete it instead if you would rather not carry a guard nothing can exercise.

**`test_sfpu_stress`** — not intended, no. The exclusion table is module-private and does not reach it, so it now carries `@skip_for_coverage` like its sibling `accuracy/test_sfpu_accuracy.py`. Gating the whole test rather than the three `Reciprocal` cases because it is a diagnostic sweep whose coverage data duplicates the unary sweep's.

File: tt_metal/tt-llk/tests/python_tests/test_eltwise_unary_sfpu.py [hunk 4]
```diff
@@ -158,58 +158,34 @@
...
 
-    # Coverage runs skip the broad profile wholesale; only the standard profile runs.
-    if mathop in BROAD_SWEEP_OPS:
-        pytest.skip(
-            reason="Broad-profile ops are not run under coverage: "
-            "https://github.com/tenstorrent/tt-llk/issues/1435"
-        )
-
-    if mathop in COVERAGE_COMPILE_SKIP_OPS:
+    if mathop in COVERAGE_SFPLOADMACRO_SKIP_OPS:
```
[the remark this answers is not in the document]
Comment (ldjurovicTT) [reply tt_metal/tt-llk/tests/python_tests/test_eltwise_unary_sfpu.py]: Fixed — `_skip_coverage_unsupported` now returns early when `TT_METAL_DISABLE_SFPLOADMACRO` is set, so `--coverage --disable-sfploadmacro` runs every `Reciprocal` variant, which is the config the evidence table already has at 153 passed / 0 failed.

Scoped as an early return with a note that every entry in the table is macro-mediated today, and to revisit it if one that is not is ever added — rather than folding the condition into the per-op lookup, which would read as if the env var were part of the exclusion key.

Probed all 36 `arch × coverage × macro-disable × op` combinations directly against the helper: the only skip is Blackhole + coverage + macro enabled + `Reciprocal`.
