### ISSUE TITLE
[Bug Report] Cannot import ttnn in python

### ISSUE THREAD

**Issue by jeongu-moreh** [tenstorrent/tt-metal#11607]
**Describe the bug**
Attempt to import `ttnn` in python causes an import error.

**To Reproduce**
1. Build tt-metal on 5711ea7 (current main) with `build_metal.sh`
2. Import `ttnn` in python
3. Error
```
>>> import ttnn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/tt-moreh/tt-metal/ttnn/ttnn/__init__.py", line 20, in <module>
    import ttnn._ttnn
ImportError: libnng.so.1: cannot open shared object file: No such file or directory
```

**Expected behavior**
`ttnn` is imported without an error.

**Additional context**
It seems that the problem is caused by PR #11496 (not clear)

**Comment by Aswinmcw** [comment]
Hi @jeongu-moreh , can you try the below command
```
cd build
ninja install
```

**Comment by jeongu-moreh** [comment]
It works on latest main.

**Comment by jeongu-moreh** [comment]
Sorry for the confusion. `import ttnn` still produces an error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/tt-moreh/tt-metal/ttnn/ttnn/__init__.py", line 229, in <module>
    import ttnn.operations
  File "/home/ubuntu/tt-moreh/tt-metal/ttnn/ttnn/operations/__init__.py", line 11, in <module>
    _module = loader.find_spec(module_name).loader.load_module(module_name)
  File "/home/ubuntu/tt-moreh/tt-metal/ttnn/ttnn/operations/transformer.py", line 9, in <module>
    SDPAProgramConfig = ttnn._ttnn.operations.transformer.SDPAProgramConfig
AttributeError: module 'ttnn._ttnn.operations.transformer' has no attribute 'SDPAProgramConfig'
```

**Comment by jeongu-moreh** [comment]
> Sorry for the confusion. `import ttnn` still produces an error ([f0bbd07](https://github.com/tenstorrent/tt-metal/commit/f0bbd07841f72c474df4489c7589339699b07ed7)):

My mistake.
