### ISSUE TITLE
[test_binaryng_fp32.py:479] | Sanity tests | ttsim-tests / TTNN ttnn eltwise group 3 - wormhole_b0

### ISSUE THREAD

**Issue by ebanerjeeTT** [tenstorrent/tt-metal#47959]
## CI Failure Report

**Summary:** [CI] ttnn.eq on bfloat16 produces wrong results for special float values (0, -0, inf, -inf, nan)

**Workflow:** Sanity tests
**Job:** ttsim-tests / TTNN ttnn eltwise group 3 - wormhole_b0

### Regression timeline

- **Last passing commit:** `93f082b106f7` — 2026-06-24T13:13:04Z — [run](https://github.com/tenstorrent/tt-metal/actions/runs/28101076868)
- **First failing commit:** `390e35fbb69d` — 2026-06-24T13:13:05Z — [job](https://github.com/tenstorrent/tt-metal/actions/runs/28101078547/job/83231499385)
- **Most recent failing commit:** `1ab43ff76ace` — 2026-06-24T13:18:05Z — [job](https://github.com/tenstorrent/tt-metal/actions/runs/28101387249/job/83226892868)

### Failing job URLs (last 4 runs)

- https://github.com/tenstorrent/tt-metal/actions/runs/28101387249/job/83226892868
- https://github.com/tenstorrent/tt-metal/actions/runs/28101200257/job/83224901709
- https://github.com/tenstorrent/tt-metal/actions/runs/28101078031/job/83225477734
- https://github.com/tenstorrent/tt-metal/actions/runs/28101078547/job/83231499385

### Failing test path(s)

- `tests/ttnn/unit_tests/operations/eltwise/test_binaryng_fp32.py::test_special_values[dtype=bfloat16-op_name=eq]`

### Error excerpt (terminal failure from logs)

```
FAILED tests/ttnn/unit_tests/operations/eltwise/test_binaryng_fp32.py::test_special_values[dtype=bfloat16-op_name=eq] - AssertionError: Mismatches found

________________ test_special_values[dtype=bfloat16-op_name=eq] ________________

>       assert torch.equal(z_torch, tt_out), "Mismatches found"
E       AssertionError: Mismatches found
E       assert False
E        +  where False = <built-in method equal of type object at 0x7fcdcb782c00>(
             tensor([ True, False, False, False, False, False,  True, ...]),
             tensor([1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., ...], dtype=torch.bfloat16))

tests/ttnn/unit_tests/operations/eltwise/test_binaryng_fp32.py:479: AssertionError
```

The test exercises `ttnn.eq` on `bfloat16` tensors containing all combinations of special floating-point values (`0.0`, `-0.0`, `inf`, `-inf`, `nan`, `1.0`, `-1.0`). The TTNN device result (bfloat16 float `1.0`/`0.0`) does not match PyTorch's boolean output for certain pairs — notably `-0.0 == 0.0` and similar NaN/inf edge cases.

### Reproduction steps

```bash
# From the repo root, with the ttsim environment active:
pytest tests/ttnn/unit_tests/operations/eltwise/test_binaryng_fp32.py::test_special_values \
    -k 'dtype=bfloat16 and op_name=eq' \
    -xv -m 'not disable_fast_runtime_mode'
```

The CI job runs the broader eltwise group with:
```bash
pytest tests/ttnn/unit_tests/operations/eltwise -xv --splits 4 --group 3 -m "not disable_fast_runtime_mode"
```

### Notes

- The mismatch is between PyTorch's boolean tensor and ttnn's bfloat16 float output — the `eq` op on `bfloat16` appears to produce float `1.0`/`0.0` instead of a boolean tensor, and some equality comparisons involving `-0.0`, `nan` or `inf` give wrong values.
- `float32` variant (`dtype=float32-op_name=eq`) **passes** in all runs; only `bfloat16` is affected.
- **Determinism check:**
  - Run 1 (line 24508): `FAILED test_binaryng_fp32.py::test_special_values[dtype=bfloat16-op_name=eq] - AssertionError: Mismatches found`
  - Run 2 (line 25315): `FAILED test_binaryng_fp32.py::test_special_values[dtype=bfloat16-op_name=eq] - AssertionError: Mismatches found`
  - Run 3 (line 25315): `FAILED test_binaryng_fp32.py::test_special_values[dtype=bfloat16-op_name=eq] - AssertionError: Mismatches found`
  - Run 4 (line 24490): `FAILED test_binaryng_fp32.py::test_special_values[dtype=bfloat16-op_name=eq] - AssertionError: Mismatches found`

`Auto-triage-workflow: Sanity tests`
`Auto-triage-job-name: ttsim-tests / TTNN ttnn eltwise group 3 - wormhole_b0`

## About this issue (automated CI auto-triage)
This issue was opened and assigned by an automated AI system. It posts through a bot token, so notifications may look like they come from a person, but they are automated.

The owner is selected from recent commit history and job-ownership data. It reflects who is *likely able to fix or route* this, not necessarily who caused it, so it can be imperfect.

**If this was assigned to the wrong person, you can:**
- Comment `REASSIGN OWNER: <why this is outside your area / which team or test-area it belongs to>` and the system will automatically re-route it to a better-suited owner.
- Unassign yourself (this stops notifications to you).
- Close the issue if it is not a real or relevant failure.

The assigned owner is reminded about every 3 days until the issue is resolved. Full guide: https://tenstorrent.atlassian.net/wiki/spaces/MI6/pages/2545221692/Auto-Triage+Info

**Comment by Aswinmcw** [comment]
## Root Cause Analysis

Same root cause as #47958 (Blackhole), reproduced here on Wormhole B0 (ttsim).

### Summary

Two pre-existing bugs in the bfloat16 `eq` kernel, newly landing in CI group 3 due to pytest split boundary shift from PR #47203 adding 48 new parametrized test cases to the eltwise test collection.

**Bug 1 — Output dtype mismatch:** `ttnn.eq` on `bfloat16` returns a bfloat16 float tensor (`1.0`/`0.0`) instead of a bool tensor. The float32 path correctly returns bool. `torch.equal` fails immediately on dtype mismatch regardless of values.

**Bug 2 — Special float semantics:** The bfloat16 eq SFPU kernel does not implement IEEE 754 special-value rules: `NaN != NaN` always, and `-0.0 == 0.0`. The float32 kernel handles these correctly.

### Is this new or pre-existing?

Pre-existing since commit a8827dfd (2026-05-19). PR #47203 (2026-06-23) added 48 new parametrized tests to the eltwise suite, shifting the split group boundary and exposing these failures in group 3 for the first time.

### Fix

See #47958 for full fix guidance — the fix is identical for both architectures:
1. Force comparison op output dtype to `UINT8` (bool) for bfloat16 inputs
2. Add IEEE NaN/signed-zero handling to the bfloat16 comparison SFPU kernel

**Comment by KalaivaniMCW** [comment]
The issue was caused by https://github.com/tenstorrent/tt-metal/pull/43616 ("[QUASAR] Semaphores + synchronization for unpack_to_dest") which accidentally enabled the integer-FPU datacopy MOP on WH/BH by passing `UnpackToDestEn=true` as `is_int_fpu_en` in `copy_tile_to_dst_init_short`. This corrupted `bfloat16` special value bit patterns (NaN, -0.0, inf) during the tile copy into DST. The fix (45f1d51ebb1, PR [#47985](https://github.com/tenstorrent/tt-metal/pull/47985)) was merged
Latest passing run on main https://github.com/tenstorrent/tt-metal/actions/runs/28154191955/job/83380788604
