### ISSUE TITLE
[Bug Escape] 829141990__910a671d — test_single_layer_model (Gemma-4-26B-A4B unit tests)

### ISSUE THREAD

**Issue by ebanerjeeTT** [tenstorrent/tt-metal#48127]
## Bug Escape: 829141990__910a671d

**Test:** `test_single_layer_model`
**Hardware:** BH quietbox 2
**Escape type:** horizontal (Test L4 → Fix L4)
**Fix PR:** https://github.com/tenstorrent/tt-metal/pull/47248 — Restore greedy_only warmup API after #45355 merge.
**Fix commit:** `910a671d`

### Failure (before fix)

**Error:** `TypeError: prefill_forward() got an unexpected keyword argument 'valid_seq_len'`
**Workflow:** [(Tier 2) Models Unit](https://github.com/tenstorrent/tt-metal/actions/runs/27875389236)
**Failing job:** [Gemma-4-26B-A4B unit tests [bh_quietbox_2]](https://github.com/tenstorrent/tt-metal/actions/runs/27875389236/job/82493969921)

### Probes

| | Run | Result |
|---|---|---|
| BEFORE (failing) | [27875389236](https://github.com/tenstorrent/tt-metal/actions/runs/27875389236/job/82493969921) | FAIL |
| AFTER (fixed) | [27875389779](https://github.com/tenstorrent/tt-metal/actions/runs/27875389779/job/82493968035) | PASS |

### Evidence

Introduced by PR #45355. `test_single_layer_model` calls `prefill_forward()` with the `valid_seq_len` keyword argument; PR #45355 changed the API and removed that parameter. Fix PR #47248 restored the greedy_only warmup API. BEFORE at SHA 63d0eaad (PCC 0.9999 expected). AFTER: PASS at 1f33d445.

---

_Tracked by the BrAIn bug-escape campaign._
_Full lists: [Vertical Bug Escapes](https://tenstorrent.atlassian.net/wiki/spaces/METALFOUNDRY/pages/2424012846) | [Horizontal Bug Escapes](https://tenstorrent.atlassian.net/wiki/spaces/METALFOUNDRY/pages/2461597780)_

**Comment by ebanerjeeTT** [comment]
Closing — tracked via auto-bug-escapes label. No active remediation needed.
