### PR TITLE
Remove get_welford_params method from group_norm DRAM tests

### PR DESCRIPTION
**Pull request by bjanjicTT**
### Ticket
Failed CI job https://github.com/tenstorrent/tt-metal/actions/runs/19025402821/job/54342431983
`ERROR tests/ttnn/nightly/unit_tests/operations/fused/test_group_norm_DRAM.py - AttributeError: module 'tests.ttnn.unit_tests.operations.fused.test_group_norm_DRAM' has no attribute 'get_welford_params'`

### Problem description
The CI job https://github.com/tenstorrent/tt-metal/actions/runs/19025402821/job/54342431983 failed due to a missing attribute `get_welford_params`. 

### What's changed
Regression caused by commit: https://github.com/tenstorrent/tt-metal/commit/e216dd6fdfb415f28fe25b545050d7e9306ba6ae#diff-a22abe157290d6a8a70b6b080ac2381031fb6cee2f688216e45e19a2deeaa4ec

The method `get_welford_params` was removed from the file `tests/ttnn/nightly/unit_tests/operations/fused/test_group_norm_DRAM.py` and replaced with`("legacy", "welford_normal", "welford_reciprocal")` as shown https://github.com/tenstorrent/tt-metal/blob/edff745a6345ae98ee9e5c6783077d3990dafd73/tests/ttnn/unit_tests/operations/fused/test_group_norm_DRAM.py#L61

One test case is failing due to a lower PCC on BH 150 (full grid). 
**PCC drops to 0.9565977077851433 for `welford_normal` and `welford_reciprocal`**
```
"N, C, H, W, num_groups, num_out_blocks, cores_y, cores_x",
(1, 128 // 4, 1024, 1024, 32 // 4, 8, 8, 8), 
```

Regression caused by commit: https://github.com/tenstorrent/tt-metal/commit/e216dd6fdfb415f28fe25b545050d7e9306ba6ae#diff-a22abe157290d6a8a70b6b080ac2381031fb6cee2f688216e45e19a2deeaa4ec

### Checklist
- [ ] [Nightly tt-metal L2 tests] https://github.com/tenstorrent/tt-metal/actions/runs/19033735744

### CODE REVIEW

File: tests/ttnn/nightly/unit_tests/operations/fused/test_group_norm_DRAM.py [hunk 1]
```diff
@@ -36,11 +34,11 @@
         (1, 512 // 4, 512, 512, 32 // 4, 8, 8, 8),
         (1, 256 // 4, 512, 512, 32 // 4, 4, 8, 8),
         (1, 256 // 4, 1024, 1024, 32 // 4, 16, 8, 8),
-        (1, 128 // 4, 1024, 1024, 32 // 4, 8, 8, 8),
+        # (1, 128 // 4, 1024, 1024, 32 // 4, 8, 8, 8), #PCC drops to 0.9565977077851433 of welford_normal and welford_reciprocal
```
Comment (iwroszTT) [inline tests/ttnn/nightly/unit_tests/operations/fused/test_group_norm_DRAM.py]: Could you create an issue to track the PCC drop? Please add the issue number into the comment.

Comment (ipotkonjak-tt) [inline tests/ttnn/nightly/unit_tests/operations/fused/test_group_norm_DRAM.py]: If the test is failing due to use of welford algorithm I'd rather add a pyskip for those two versions of the op and still test the vanilla group norm version for this shape, as this is a use case from an actual model. In addition to this appropriate issue needs to be made for the op owners.

You can mention the issue in the reasoning behind the pyskip

cc: @cglagovich @jonathansuTT

**Comment by edwinleeTT** [comment]
A fix for bad PCC in Group Norm DRAM tests on Blackhole recently went in at https://github.com/tenstorrent/tt-metal/commit/4f7712de246ba6cc82bb978512e9c23a5d6aef9f. It's the next commit after the commit used in the failing CI run. Just to confirm, is this PCC issue still seen with this change?

**Comment by rmillerTT** [comment]
@bjanjicTT get_welford_params is not in main anymore. Please confirm on your end and close this PR if needed. As @edwinleeTT said, there was a fix that went in earlier today for the bad PCC. APC and BPC should be fully passing now.

**Review by bbradelTT — APPROVED** [review]

File: tests/ttnn/nightly/unit_tests/operations/fused/test_group_norm_DRAM.py (hunk 1 above)
Comment (bjanjicTT) [reply tests/ttnn/nightly/unit_tests/operations/fused/test_group_norm_DRAM.py]: Seams that this test is not executed anywhere. I'm not sure if it should be executed in some nightly workflows.

Comment (bjanjicTT) [reply tests/ttnn/nightly/unit_tests/operations/fused/test_group_norm_DRAM.py]: Seams that this test is not executed anywhere. I'm not sure if it should be executed in some nightly workflows. It fails in local run on blackhole 150.

**Comment by bjanjicTT** [comment]
@rmillerTT This appears to be leftover from the removal. @edwinleeTT With those changes, test fails locally. It seems it's not part of any CI workflow.

File: tests/ttnn/nightly/unit_tests/operations/fused/test_group_norm_DRAM.py (hunk 1 above)
Comment (bbradelTT) [reply tests/ttnn/nightly/unit_tests/operations/fused/test_group_norm_DRAM.py]: Sorry, I'll add this to the l2 nightly workflow.

**Comment by bjanjicTT** [comment]
Follow up ticket created by @bbradelTT 
https://github.com/tenstorrent/tt-metal/issues/31782
https://github.com/tenstorrent/tt-metal/issues/31783
